module.exports = {
  EXPECTED_BOOKS: [
    "The Fellowship Of The Ring",
    "The Two Towers",
    "The Return Of The King",
  ],

  EXPECTED_MOVIES: [
    "The Lord of the Rings Series",
    "The Hobbit Series",
    "The Unexpected Journey",
    "The Desolation of Smaug",
    "The Battle of the Five Armies",
    "The Two Towers ",
    "The Fellowship of the Ring",
    "The Return of the King",
  ],

  EXPECTED_QUOTES: [
    "Deagol!",
    "Deagol!",
    "Deagol!",
    "Give us that! Deagol my love",
    "Why?",
    "Because', it's my birthday and I wants it.",
    "Arrghh!",
    "They cursed us",
    "Murderer!",
    "'Murderer' they called us. They cursed us and drove us away.",
    "Pull it in! Go on, go on, go on, pull it in!",
    "Oh Smeagol Ive got one! Ive got a fish Smeagol, Smeagol!",
    "My precious.",
    "Gandalf?",
    "Oooohhh!",
    "Frodo!",
    "Aaaahh!",
    "and cool, so nice for feet' and we only wish to catch a fish, so juicy sweet.",
    "Gimli!",
    "My precious!",
    "Wake up! Wake up! Wake up sleepies! We must go, yes, we must go at once.",
    "Haven't you had any sleep Mr Frodo?",
    "And we forgot the taste of bread, the sound of trees and the softness of the wind. We even forgot our own name.",
    "Gollum' Gollum' Gollum', and we wept precious. We wept to be so alone.",
    "Not before Mr Frodo's had something to eat.",
    "No time to lose silly!",
    "Come on! Must go! No time!",
    "And I've gone and had too much. It must be getting late.",
    "No, it isn't. It isn't midday yet. The days are growing darker.",
    "Here.",
    "What about you?",
    "Oh no, I'm not hungry, leastways not for lembas bread.",
    "Sam!",
    "Aragorn!",
    "Now come the days of the King. May they be blessed.",
    "This day does not belong to one man, but to all. Let us together rebuild this world, that we may share in the days of peace.",
    "Et E'rello Endorenna ut'lien. Sinome maruvan ar Hildinyar tenn' Ambar-metta!",
    "Hannon le.",
    "My friends, you bow to no-one.",
    "And thus it was a Fourth Age of Middle Earth began. And the Fellowship of the Ring, though eternally bound by friendship and love was ended. Thirteen months to the day since Gandalf sent us on our long journey we find ourselves looking upon a familiar sight.",
    "Alright!",
    "We were home.",
    "Hey watch the pumpkin.",
    "The journey home.",
    "Oh alright, but we don't have that much left. We have to be careful or we are going to run out. You go ahead and eat that Mr Frodo. I've rationed it, there should be enough.",
    "Come Hobbitses, very close now. Very close to Mordor. No safe places here. Hurry.",
    "It's good. Definitely from the Shire. Longbottom leaf eh?",
    "uhh huh, I feel like I'm back at the Green Dragon.",
    "Mmmm, Green Dragon!",
    "For what?",
    "Goodnight lads.",
    "Welcome, my lords to Isengard!",
    "You young rascals. A merry hunt you've led us on and now we find you feasting and ' and smoking!",
    "Hmm?",
    "Only, you've never done a hard day's work.",
    "Ahaha!",
    "How do you pick up the threads of an old life? How do you go on, when in your heart you begin to understand there is no going back? There are some things that time cannot mend. Some hurts that go too deep, that have taken hold.",
    "Mr Frodo? What is it?",
    "It's been four years to the day since Weathertop, Sam. It's never really healed.",
    "A mug of ale in my hand. Putting my feet up on a settle after a hard day's work.",
    "There and Back Again, a Hobbits tale by Bilbo Baggins and the Lord of the Rings by Frodo Baggins. You finished it.",
    "Not quite. There's room for a little more.",
    "Bilbo once told me his part in this tale would end. That each of us must come and go in the telling. Bilbo's story was now over. There would be no more journeys for him, save one.",
    "To the harbour Bilbo. The elves have accorded you a special honour. A place on the last ship to leave Middle Earth.",
    "Salted pork'",
    "Hobbits!",
    "We're under orders from Treebeard who's taken over management of Isengard.",
    "Tell me again lad, where are we going?",
    "Frodo, any chance of seeing that old Ring of mine again? The one I gave you?",
    "Hoooom, young master Gandalf, I'm glad you've come. Wood and water, stock and stone I can master, but there is a Wizard to manage here locked in his tower",
    "We are sitting on a field of victory enjoying a few well earned comforts, The salted pork is particularly good.",
    "Show yourself.",
    "Well then let's just have his head and be done with it.",
    "Be careful. Even in defeat, Saruman is dangerous.",
    "You have fought many wars and slain many men Theoden King and made peace afterwards. Can we not take counsel together as we once did, my old friend?Can we not have peace you and I?",
    "We shall have peace'. We shall have peace when you answer for the burning of the Westfold and the children that lie dead there! We shall have peace when the lives of the soldiers whose bodies were hewn even as they lay dead against the gates of the Hornburg' are avenged! When you hang from a gibbet for the sport of your own crows' we shall have peace!",
    "Gibbets and crows! Dotard! What do you want Gandalf Grahame? Let me guess' the key of Orthanc? Or perhaps the keys of Barad D'r itself? Along with the crowns of the seven Kings and the rods of the Five Wizards!",
    "No, we need him alive. We need him to talk.",
    "I'm sorry uncle. I'm afraid I lost it.",
    "Your treachery has already cost many lives. Thousands more are now at risk. But you could save them Saruman. You were deep in the enemy's counsel.",
    "I Aear c'n ven na mar.",
    "I think I'm quite ready for another adventure.",
    "Farewell my brave Hobbits. My work is now finished. Here at last, on the shores of the sea, comes the end of our Fellowship. I will not say do not weep for not all tears are an evil. It is time Frodo.",
    "What does he mean?",
    "Oh! Well here is a sight I have never seen before.",
    "The power of the three rings is ended. The time has come for the dominion of men.",
    "Oh, pity. (He sighs.) I would have like to have held it one last time.",
    "We set out to save the Shire Sam and it has been saved, but not for me.",
    "You don't mean that. You can't leave.",
    "So you have come here for information. I have some for you. Something festers in the heart of Middle Earth. Something that you have failed to see. But the great eye has seen it! Even now he presses his advantage. His attack will come soon. You are all going to die! But you know this don't you Gandalf? You cannot think that this Ranger will ever sit upon the throne of Gondor. This exile, crept from the shadows will never be crowned King. Gandalf does not hesitate to sacrifice those who are closest to him' those he professes to love! Tell me, what words of comfort did you give the Halfling before you sent him to his doom? The path that you have set him on can only lead to death.",
    "Save your pity and your mercy. I have no use for it!",
    "Saruman'.. your staff is broken!",
    "Grima! You need not follow him! You were not always as you are now. You were once a man of Rohan. Come down.",
    "I've heard enough! Shoot him! Stick an arrow in his gob!",
    "The last pages are for you Sam.",
    "Free? He will never be free!",
    "No!",
    "My dear Sam, you cannot always be torn in two. You will have to be one and whole for many years. You have so much to enjoy and to be and to do. Your part in the story will go on.",
    "Well, I'm back.",
    "I didn't think it would end this way.",
    "End? No, the journey doesn't end here. Death is just another path, one that we all must take. The grey rain curtain of this world rolls back and all turns to silvered glass. And then you see it.",
    "A man of Rohan? What is the house of Rohan but a thatched barn where brigands drink in the reek and their brats roll on the floor with the dogs? The victory at Helms Deep does not belong to you Theoden Horse Master. You are a lesser son of greater sires!",
    "Grima'. Come down! Be free of him!",
    "No! Come down Saruman and your life will be spared!",
    "What? Gandalf? See what?",
    "Rally to me! To meeee!",
    "Feast on his flesh.",
    "I will kill you if you touch him.",
    "The City has fallen silent. There is no warmth left in the sun.",
    "It grows so cold.",
    "It's just the damp of the first spring rain.",
    "No. No it isn't.",
    "Well, that's not so bad.",
    "White shores and beyond, a far green country under a swift sunrise.",
    "I do not believe this darkness will endure.",
    "Look! The Orcs, they're moving off!",
    "Get down cur!",
    "Ah!",
    "Saruman! You were deep in the enemy's counsel. Tell us what you know!",
    "You withdraw your guard and I will tell you where your doom will be decided. I will not be held prisoner here!",
    "Send word to all our allies and to every corner of Middle Earth that still stands free. The enemy moves against us. We need to know where he will strike.",
    "The filth of Saruman is washing away. Trees will come back to live here. Young trees. Wild trees.",
    "Pippin!",
    "Bless my bark!",
    "Peregrin Took. I'll take that my lad! Quickly now!",
    "Do not come between the Nazg'l and his prey.",
    "Late as usual, pirate scum. There's knifework here needs doing. Come on you sea rats, get off your ships.",
    "You see Mr Frodo some luck at last!",
    "Move it, you slugs!",
    "Come on! Faster!",
    "Come along you scum! I'll whip you down to the bone! Come on! What have I told you. Get up! Come on you slugs! You two are going straight to the front line! Move it, come on! Fall in! Move it! Move it! Move it!",
    "To the gate you slugs, now move it! Don't you know we're at war?",
    "Company halt! Inspection!",
    "You fool! No man can kill me. Die now!",
    "There's plenty for the both of us, may be best Dwarf win!",
    "I am no man!",
    "Mr Frodo!",
    "Sam! Help me!",
    "Stand up Mr Frodo. Stand up!",
    "Get off of me! Nobody pushes me you filthy maggot! Get off of me!",
    "Retreat! The city is breached. Fall back to the second level. Get the women and children out. Get them out. Retreat.",
    "Come on, come on!",
    "Move into the city. Kill all in your path.",
    "Break it up! Break it up!",
    "Oy! I'll have your guts if you don't shut this rabble down!",
    "It's so heavy!",
    "Oh no! What do I do?, What do I do?",
    "Hit me! Hit me Sam! Start fighting!",
    "Go Sam. Now!",
    "Take them down!",
    "Fight! Fight to the last man. Fight for your lives.",
    "Gandalf! Gandalf! Denethor has lost his mind. He's burning Faramir alive!",
    "Move along scum!",
    "Get back in the line you maggots! Get back in the line you slugs!",
    "Up! Quickly!",
    "Go back to the abyss! Fall into the nothingness that awaits you and your master!",
    "Do you not know death when you see it, old man?, This is my hour!",
    "I can't! I can't' I can't manage the Ring Sam. It's' it's' such a weight to carry. It's such a weight.",
    "We're going that way, straight as we can. There's no point carrying anything we're not sure to need.",
    "Mr Frodo, look. There is light and beauty up there that no shadow can touch.",
    "Take mine. There's a few drops left.",
    "There will be none left for the return journey.",
    "I don't think there will be a return journey Mr Frodo.",
    "Frodo, get down! Hide!",
    "AAAAhhh!",
    "You have failed! The world of men will fall.",
    "Gandalf!",
    "Where are they?",
    "Frodo!",
    "Is there any in this rout with authority to treat with me?",
    "We do not come to treat with Sauron, faithless and accursed. Tell your master this. The armies of Mordor must disband. He is to depart these lands, never to return.",
    "Let the Lord of the Black Land come forth! Let justice be done upon him!",
    "Courage Merry. Courage for our friends.",
    "Form ranks you maggots. Form ranks. Pikes in front, archers behind.",
    "Eomer, take your Eored down the left flank",
    "Flank ready!",
    "Ride now, ride now! Ride! Ride for ruin and the world's ending! DEATH!",
    "DEATH!",
    "DEATH!",
    "DEATH!",
    "DEATH!",
    "DEATH!",
    "Whatever happens, stay with me. I'll look after you.",
    "Gamling, follow the King's banner down the centre. Grimbold! Take your company right after you pass the wall. Forth and fear no darkness! Arise! Arise riders of Theoden. Spears shall be shaken, shields shall be splintered, a sword day, a red day ere the sun rises!!",
    "My master Sauron the Great bids thee welcome.",
    "Silence!",
    "No!",
    "Silence!",
    "The Halfling was dear to thee I see. Know that he suffered greatly at the hands of his host. Who would've thought one so small could endure so much pain? And he did Gandalf, he did.",
    "You may go no further.",
    "You will not enter Gondor",
    "Frodo!",
    "Frodo!",
    "Legolas, fire a warning shot past the boson's ear.",
    "Mind your aim.",
    "Oh! That's it, right, we warned you! Prepare to be boarded!",
    "Aha! Old Greybeard! I have a token I was bidden to show thee.",
    "Who are you to deny us passage?",
    "Boarded, by you and whose army?",
    "Forth Eorlingas!",
    "DEATH!",
    "CHAAAAARGE!",
    "Set a fire in our flesh!",
    "Stay this madness!",
    "Fire at will!",
    "You may triumph in the field of battle for a day, but against the power that has risen in the east, there is no victory!",
    "FIRE!",
    "NOOOOOO, you will not take my son from me!",
    "Aaaaaahhhh!",
    "So passes Denethor, son of Ecthelion.",
    "DEEEEAAATH!",
    "NO! Aaahhh",
    "Faramir!",
    "And who is this? Isildur's heir? It takes more to make a King than a broken Elvish blade.",
    "I guess that concludes negotiations.",
    "In there.",
    "I do not believe it. I will not.",
    "This army.",
    "What is this place?",
    "I can't go back.",
    "What's that smell.",
    "Orcses' filth. Orcses come in here sometimes.",
    "Now that I'm here I don't think I want to.",
    "It's the only way. Go in' or go back.",
    "Hurry! This way.",
    "Smeagol?",
    "Over here.",
    "Master must go inside the tunnel.",
    "You'll see. Oh yes, you will see.",
    "Re-form the line! Re-form the line!",
    "Sound the charge. Take them head-on. Chaaarge!",
    "Ah aah! Its sticky, what is it?",
    "Take the reins, pull him left. LEFT!",
    "Make safe the city.",
    "Bring it down! Bring it down! Bring it down!",
    "Merry!",
    "Smeagol? SMEAGOL! SMEAGOL!",
    "Sam.",
    "Ow!",
    "Cut him down!",
    "Aim for the heads!",
    "Aiya E'rendil Elenion Ancalim'",
    "Naughty little fly. Why does he cry?,Caught in a web. Soon you'll be eaten.",
    "Drive them to the river.",
    "It wasn't us. It wasn't us. Smeagol wouldn't hurt master. We promised. You must believe us. It was the precious. The precious made us do it.",
    "I have to destroy it Smeagol. I have to destroy it for both our sakes.",
    "NO! Aaaaaaaaa.",
    "And you Frodo Baggins, I give you the light of E'rendil, our most beloved star. May it be a light for you in dark places, when all other lights go out.",
    "I'm so sorry Sam. I'm so sorry.",
    "NO!",
    "One that is cursed. Long ago the men of the mountains swore an oath to the last King of Gondor, to come to his aid, to fight. But when the time came, when Gondor's need was dire, they fled vanishing into the darkness of the mountain. And so Isildur cursed them, never to rest until they had fulfilled their pledge. Who shall call them from the grey twilight, the forgotten people? The heir of him to whom the oath they swore. From the North shall he come, need shall drive him. He shall pass the door to the Paths of the Dead.",
    "Got away did it precious? Not this time. Not this time.",
    "What kind of army would linger in such a place?",
    "The very warmth of my blood seems stolen away.",
    "The way is shut. It was made by those who are dead, and the dead keep it. The way is shut.",
    "Brego!",
    "I do not fear death!",
    "The scouts report Minas Tirith is surrounded. The lower level's in flames. Everywhere, legions of the enemy advance.",
    "This task was appointed to you, Frodo of the Shire. If you do not find a way, no one will.",
    "Time is against us. Make ready!",
    "Take heart Merry. It will soon be over",
    "My lady. You are fair and brave and have much to live for, and many who love you. I know it is too late to turn aside. I know there is not much point now in hoping. If I were a knight of Rohan capable of great deeds'but I'm not. I'm a Hobbit. And I know I can't save Middle Earth. I just want to help my friends; Frodo, Sam, Pippin. More than anything I wish I could see them again.",
    "Make haste. We ride through the night.",
    "Back to the gate! Hurry!",
    "To battle",
    "Well this is a thing unheard of. An elf will go underground, where a dwarf dare not. Oh. Oh, I'd never hear the end of it.",
    "Prepare to move out!",
    "All my friends have gone to battle. I would be ashamed to be left behind.",
    "It is a three-day gallop to Minas Tirith and none of my riders can bear you as a burdon.",
    "I want to fight!",
    "I will say no more.",
    "Ride with me!",
    "My lady!",
    "To battle",
    "We must ride light and swift. It is a long road ahead and man and beast must reach the end with the strength to fight.",
    "Ride! Ride now to Gondor.",
    "What is it? What do you see?",
    "Little Hobbits do not belong in war Master Meriadoc.",
    "Where?",
    "I see shapes of men and of horses.",
    "Do not look down.",
    "Pale banners like shreds of cloud. Spears rise like winter thickets through a shroud of mist. The dead are following. They have been summoned.",
    "The dead? Summoned? I knew that! Huh. Huh. Very good. Very good. Legolas!",
    "Who enters my domain?",
    "One who will have your allegiance.",
    "You will suffer me!",
    "The dead do not suffer the living to pass.",
    "The way is shut! It was made by those who are dead. And the dead keep it. (The Ghostly army closes around them) The way is shut! Now you must die!",
    "Form up, move out! Form up, move out!",
    "My lord!",
    "Hail to you sire!",
    "I bring 500 men from the Westfold my lord.",
    "We have 300 more from Fenmarch, Theoden King.",
    "That blade was broken!",
    "It has been remade. Fight for us and regain your honour. What say you? What say you?",
    "None but the King of Gondor may command me!",
    "I am Isildur's heir. Fight for me and I will hold your oaths fulfilled. What say you?",
    "Make way for the King! Make way, the King is here",
    "I summon you to fulfil your oath!",
    "Ach! You waste your time Aragorn. They had no honour in life and they have none now in death.",
    "Legolas! Run!",
    "We fight!",
    "Open the gate, quick!",
    "Quick! Hurry!",
    "Faramir! Say not that he has fallen.",
    "They were outnumbered! None survived.",
    "Stand you traitors!",
    "Out!",
    "Where are the riders from Snowbourn?",
    "None have come my lord.",
    "Six thousand spears, less than half of what I had hoped for.",
    "You have my word! Fight and I will release you from this living death! What say you?",
    "Fear. The city is rank with it! Ha ha ha ha. Let us ease their pain. Release the prisoners!",
    "The horses are restless and the men are quiet.",
    "They grow nervous in the shadow of the mountain.",
    "That road there where does that lead?",
    "It is the road to the Dimholt, the door under the mountain.",
    "Catapults! ha ha ha.",
    "More will come",
    "My sons are spent! My line has ended!",
    "Six thousand will not be enough to break the lines of Mordor.",
    "Every hour lost hastens Gondor's defeat. We have until dawn then we must ride.",
    "My line has ended!",
    "My lord!",
    "Rohan has deserted us!",
    "Theoden's betrayed me! ABANDON YOUR POSTS!FLEE! FLEE FOR YOUR LIVES!",
    "Prepare for battle. Hurry men! To the wall! Defend the wall! Over here! Return to your posts.",
    "Send these foul beasts into the Abyss.",
    "The house of Stewards has failed.",
    "We need more rubble!",
    "He needs medicine my lord!",
    "None who venture there ever return. That mountain is evil.",
    "Aragorn! Let's find some food.",
    "There. A true esquire of Rohan.",
    "I'm ready! Sorry. It isn't all that dangerous. It's not even sharp.",
    "He's alive!",
    "Stay where you are!",
    "To the smithy, go!",
    "You should not encourage him.",
    "You should not doubt him.",
    "Sir? King Theoden awaits you my lord.",
    "Watch out!",
    "Down to the lower levels quick!",
    "I do not doubt his heart, only the reach of his arm.",
    "Why should Merry be left behind? He has as much cause to go to war as you. Why can he not fight for those he loves?",
    "Double up men!",
    "Hold them back, do not give in to fear. Stand to your posts. Fight!",
    "Not at the towers! Aim for the trolls, kill the trolls!",
    "You know as little of war as that Hobbit. When the fear takes him, and the blood and the screams and the horror of battle take hold. Do you think he would stand and fight? He would flee. And he would be right to do so. War is the province of men Eowyn.",
    "Bring them down!",
    "They called us out to fight.",
    "Fight them back!Peregrin Took! Go back to the Citadel.",
    "This is no place for a Hobbit!",
    "What are you doing you useless scum?",
    "My lord Elrond",
    "Guard of the Citadel indeed! Now back up the hill quickly. Quick!",
    "The door wont give. It's too strong.",
    "I come on behalf of one whom I love. Arwen is dying. She will not long survive the evil that now spreads from Mordor. The light of the evenstar is failing. As Sauron's power grows her strength wanes. Arwen's life is now tied to the fate of the Ring. The Shadow is upon us Aragorn. The end has come.",
    "There are none.",
    "There are those that dwell in the mountain.",
    "Murderers, traitors. You would call upon them to fight? They believe in nothing. They answer to no one",
    "I take my leave.",
    "Sauron will not have forgotten the sword of Elendil.",
    "You ride to war but not to victory. Sauron's armies ride on Minas Tirith, this you know. But in secret he sends another force, which will attack, from the river. A fleet of Corsair ships sails from the South. They will be in the city in two days. You're outnumbered Aragorn. You need more men.",
    "It will not be our end, but his.",
    "They will answer to the King of Gondor. And'ril, the Flame of the West, forged from the shards of Narsil.",
    "The blade that was broken shall return to Minas Tirith.",
    "The man who can wield the power of this sword can summon to him an army more deadly than any that walks this earth. Put aside the Ranger. Become who you were born to be 'nen i-Estel Edain.",
    "'-chebin Estel anim.",
    "I didn't think they would find any livery that would fit me.",
    "It once belonged to a young boy of the city. A very foolish one who wasted many hours slaying dragons instead of attending his studies.",
    "This was yours?",
    "Yes, it was mine. My father had it made for me.",
    "Get back there and smash it down!",
    "But nothing can breach it!",
    "It was well done. A generous deed should not be checked with cold counsel. You are to join the tower guard.",
    "What were you thinking Peregrin Took? What service can a Hobbit offer such a great lord of men?",
    "Grond, Grond, Grond, Grond, Grond!",
    "Grond, Grond, Grond, Grond!",
    "Eowyn'",
    "Why are you doing this? The war lies to the East. You cannot leave on the eve of battle. You cannot abandon the men.",
    "Grond will breach it! Bring out the wolf's head.",
    "We need you here.",
    "I have wished you joy since first I saw you.",
    "Just where do you think you're off to?",
    "Not this time. This time you must stay Gimli.",
    "Hmmmm",
    "Have you learnt nothing of the stubbornness of dwarves?",
    "You might as well accept it. We're going with you laddie. Aragorn smiles.",
    "Do you not know?",
    "It is but a shadow and a thought that you love. I cannot give you what you seek.",
    "He leaves because there is no hope.",
    "He leaves because he must.",
    "Well, I'm taller than you were then. Though, I'm not likely to grow anymore, except sideways.",
    "Why have you come?",
    "What's happening, where is he going? I don't understand. Lord Aragorn! Why does he leave on the eve of battle?",
    "It never fitted me either. Boromir was always the soldier. They were so alike he and my father. Proud, stubborn even, but strong.",
    "I think you have strength of a different kind. And one day your father will see it.",
    "And I shall not forget it! nor fail to reward that which is given. Fealty with love. Valour with honour. Disloyalty with vengeance. I do not think we should so lightly abandon the outer defences. Defences that your brother long held intact.",
    "What would you have me do?",
    "I will not yield the River and Pellenor unfought. Osgiliath must be retaken.",
    "My lord Osgiliath is over run.",
    "Much must be risked in war. Is there a Captain here who still has the courage to do his lord's will?",
    "You wish now that our places had been exchanged. That I had died and Boromir had lived.",
    "Here do I swear fealty and service to Gondor in peace or war, in living or dying, from, ' from this hour henceforth until my lord release me or death take me.",
    "No, we cannot. But we will meet them in battle nonetheless.",
    "I have left instruction. The people are to follow your rule in my stead. Take up my seat in the Golden Hall. Long may you defend Edoras, if the battle goes ill.",
    "What other duty would you have me do my lord?",
    "Duty? No. I would have you smile again, not grieve for those whose time has come. You shall live to see these days renewed, ' and no more despair",
    "Yes, I wish that.",
    "Since you are robbed of Boromir I will do what I can in his stead. If I should return, think better of me father.",
    "To few have come. We cannot defeat the armies of Mordor.",
    "Sneaking? Sneaking? Fat Hobbit is always so polite. Smeagol shows them secret ways that nobody else could find and they say 'sneak!' Sneak? Very nice friend, oh yes my precious very nice, very nice!",
    "Alright! Alright! You just startled me is all. What were you doing?",
    "Sneaking.",
    "Fine, have it your own way. I'm sorry to wake you Mr Frodo but we have to be moving on.",
    "It's dark still.",
    "It's always dark here. It's gone! The elven bread!",
    "Ech!",
    "What? That's all we have left!",
    "We can't hold them. The city is lost.",
    "What are you up to? Sneaking off are we?",
    "That will depend on the manner of your return.",
    "He took it. He must have.",
    "Smeagol? No, no, not poor Smeagol. Smeagol hates nasty elf bread.",
    "You're a lying rat! What did you do with it?",
    "He doesn't eat it. He can't have taken it.",
    "Look, what's this? , Crumbs on his jacketses. He took it!He took it! I've seen him, he's always stuffing his face when master's not looking.",
    "That's a filthy lie! You stinking, two faced sneak!",
    "Tell the men to break cover. We ride for Minas Tirith.",
    "Nazg'l!",
    "Take cover! Nazgul! Fall back. Fall back to Minas Tirith!",
    "Stop it!",
    "I'll kill him!",
    "Call me'",
    "Sam, no!",
    "No. No you're not all right, you're exhausted. It's that Gollum. It's this place. It's that thing around your neck. I could help a bit. I could carry it for a while, carry it for a while, I could carry it! I could carry it! Share the load! Share the load! Share the load!",
    "Get away!",
    "Fall back! Retreat! Retreat! Run for your lives!",
    "The age of men is over. The time of the Orc has come.",
    "I'm all right.",
    "Oh my! I'm sorry. I didn't mean it to go so far. I was just so, so angry! Here just' let's just rest a bit.",
    "Keep going. It's the Nazgul. Take cover my lord. It's coming.",
    "Sam!",
    "Its Mithrandir! The White Rider!",
    "Foreseen and done nothing!",
    "Faramir? This is not the first Halfling to have crossed your path.",
    "Pull!",
    "Mithrandir! They broke through our defences. They've taken the bridge and the West bank. Battalions of Orcs are crossing the river.",
    "It is as the Lord Denethor predicted! Long has he foreseen this doom!",
    "You've seen Frodo and Sam?",
    "No.",
    "Where? When?",
    "I don't want to keep it. I just want to help.",
    "See? See? He wants it for himself.",
    "Shut up you! Go away! Get out of here!",
    "No Sam! It's you! I'm sorry Sam.",
    "But he's a liar! He's poisoned you against me.",
    "You can't help me any more.",
    "You don't mean that.",
    "Go home.",
    "Can you sing Master Hobbit?",
    "well, yes. At least well enough for my own people. But we have no songs for great halls and evil times.",
    "Sauron's wrath will be terrible, his retribution swift.",
    "The battle for Helm's Deep is over. The battle for Middle-earth is about to begin.",
    "(looking back out to Mordor) All our hopes now lie with two little Hobbits...",
    "In Ithilien. Not two days ago. Gandalf, they're taking the road to the Morgul vale.",
    "Where does my allegiance lie if not here? This is the city of the men of N'menor. I will gladly give my life to defend her beauty, her memory, her wisdom.",
    "What does that mean? What's wrong? He looks at Gandalf.",
    "Faramir! Faramir! Your father's will has turned to madness. Do not throw away your life so rashly.",
    "Your father loves you Faramir. He will remember it before the end.",
    "And then the pass of Cirith Ungol.",
    "What you judged to be right! You sent the Ring of power into Mordor in the hands of a witless Halfling! It should have been brought back to the citadel to be kept safe. Hidden. Dark and deep in the vaults' not to be used. unless, at the uttermost end of need.",
    "I would not use the Ring. Not if Minas Tirith were falling in ruin and I alone could save her.",
    "Ever you desire to appear lordly and gracious as a King of old. Boromir would have remembered his father's need. He would have brought me a kingly gift",
    "Boromir would not have brought the Ring. He would have stretched out his hand to this thing and taking it he would have fallen.",
    "This is how you would serve your city? You would risk its utter ruin?",
    "I did what I judged to be right.",
    "And why should your songs be unfit for my halls? Come, sing me a song.",
    "Home is behind, The world ahead, And there are many paths to tread, Through shadow, to the edge of night, Until the stars are all alight. Mist and shadow cloud and shade, All shall fade, All shall, 'fade.",
    "Faramir tell me everything. Tell me all you know.",
    "March, march! March, march march!",
    "...somewhere in the wilderness.",
    "I wonder if we'll ever be put into songs or tales.",
    "What?",
    'I wonder if people will ever say, "Let\'s hear about Frodo and the Ring." And they\'ll say, "Yes! That\'s one of my favourite stories." "Frodo was really courageous, wasn\'t he, Dad? " "Yes, my boy. The most famousest of Hobbits. And that\'s saying a lot."',
    'Well, you\'ve left out one of the chief characters: "Samwise the Brave." I want to hear more about Sam.',
    "Frodo wouldn't have got far without Sam.",
    "Smeagol?",
    "So was l.",
    "Master. Master looks after us. Master wouldn't hurt us.",
    "Now, Mr. Frodo, you shouldn't make fun. I was being serious.",
    "Don't ask Smeagol. Poor, poor Smeagol.",
    '"Samwise the Brave."',
    "Master broke his promise.",
    "You know nothing of this matter!",
    "We're not going to wait for you. Come on.",
    "Father?",
    "My son! Leave me!",
    "Careful master! Careful. Very far to fall. Very dangerous are the stairs.",
    "Come master.",
    "Come to Smeagol.",
    "Mr Frodo! Get back you! Don't touch him.",
    "Master betrayed us. Wicked. Tricksy. False. We ought to wring his filthy little neck. Kill him! Kill him! Kill them both! And then we take the precious......and we be the master!",
    "He would have kept it for his own. And when he returned you would not have known your son.",
    "Send forth all legions. Do not stop the attack until the city is taken.",
    "Boromir was loyal to me! Not some wizard's pupil.",
    "Why does he hates poor Smeagol? What has Smeagol ever done to him? Master? ,Master carries a heavy burden Smeagol knows, heavy heavy burden. Fat one cannot know. He wants it. He needs it. Smeagol sees it in his eye. Very soon he will ask you for it. You will see. The fat one will take it from you!",
    "But the fat Hobbit, he knows. Eyes always watching.",
    "Yes. No! No! It's too risky. It's too risky.",
    "Where is he? Where has he gone? Hey, Gollum! Where are you?",
    "Smeagol?",
    "We could let, do it.",
    "Yes. She could do it.",
    "Yes, precious, she could. And then we takes it once they're dead.",
    "Yes. Yes. Yes.",
    "Kill them both.",
    "Come on, Hobbits. Long ways to go yet. Smeagol will show you the way.",
    "Then we stabs them out. Put out his eyeses and make him crawl.",
    "Once they're dead. Ssssssssssssssh!",
    "Stay out of the forest! Keep away from the trees!",
    "Final count.....42.",
    "Forty-two? That's not bad for a pointy-eared Elvish princeling. I myself am sitting pretty on 43.",
    "Forty-three.",
    "I will break him.",
    "Where are Theoden's riders?",
    "Will Rohan's army come? Mithrandir?",
    "Courage is the best defence that you have now.",
    "Follow me.",
    "He was twitching.",
    "Slay them all!",
    "He was twitching......because he's got my axe,embedded in his nervous system!",
    "He doesn't look too happy, does he?",
    "Not too happy at all, Merry.",
    "Still, I suppose the view would be quite nice from up there.",
    "He was already dead.",
    "What of the wizard?",
    "No, it isn't. I'm starving.",
    "Good luck trying to find something decent around here. Probably only dead rats and mouldy bread.",
    "Saruman's storeroom!",
    "I don't believe it.",
    "It can't be.",
    "lt is!",
    "Oh, yes. It's a quality establishment. I hear the staff are very good.",
    "What are you doing?",
    "Nothing. The world's back to normal, that's all.",
    "It's perfect. One barrel each. Wait. Do you think we should share it with Treebeard?",
    "Share it?,No. No. Dead plant and all that. Don't think he'd understand. Could be a distant relative.",
    "I get it. Don't be hasty.",
    "Exactly. Bar-hrum.",
    "Longbottom Leaf. The finest pipe-weed in South Farthing.",
    "The Shire must truly be a great realm Master Gamgee......where gardeners are held in high honor.",
    "What road will you take once you reach the woods?",
    "Gollum says there's a path......near Minas Morgul that climbs up into the mountains.",
    "Cirith Ungol?,",
    "ls that its name?",
    "No. No! Yes.",
    "This is the old sewer. Runs right under the river through to the edge of the city. You'll find cover in the woods there.",
    "Captain Faramir......you have shown your quality, sir.",
    "The very highest.",
    "I must.",
    "lt is the only way. Master says we must go to Mordor, so we must try.",
    "Thank you.",
    "Go, Frodo. Go with the goodwill of all Men.",
    "Frodo......they say a dark terror dwells in the passes above Minas Morgul. You cannot go that way.",
    "May death find you quickly if you bring them to harm.",
    "Come on, keep up.",
    "Mr. Frodo didn't mean for them Rangers to hurt you. You know that, don't you? He was trying to save you, see?",
    "Very decent of you. Very decent, indeed Gollum.",
    "Faramir! Orcs have taken the eastern shore. Their numbers are too great. By nightfall we will be overrun.",
    "Mr. Frodo?",
    "It's calling to him, Sam. His Eye is almost on me.",
    "Hold on, Mr. Frodo. You'll be all right.",
    "Take them to my father. Tell him Faramir sends a mighty gift. A weapon that will change our fortunes in this war.",
    "No, no, no hard feelings. Gollum, Gollum. Yes, master. Nice Hobbits.",
    "So there's no hard feelings. Forgive and forget.",
    "Save me?",
    "Do you want to know what happened to Boromir?,You want to know why your brother died? He tried to take the Ring from Frodo after swearing an oath to protect him!He tried to kill him! The Ring drove your brother mad!",
    "Watch out!",
    "Mr. Frodo?",
    "They're here.",
    "Nazgul!",
    "They've come.",
    "The fortress is taken. It is over.",
    "You said this fortress would never fall while your men defend it. They still defend it. They have died defending it.",
    "They're past the door!",
    "They are breaking in!",
    "Is there no other way for the women and children to get out of the caves?",
    "Stay here. Keep out of sight. Take cover!",
    "Is there no other way?",
    "Nan Barad! Nan Barad! Haldir, nan Barad! (",
    "What are you doing? What are you stopping for?",
    "Nan Barad! To the Keep!",
    "Haldir!",
    "So much death. What can Men do against such reckless hate?",
    "Ride out with me. Ride out and meet them.",
    "Tell the women and children to make for the mountain pass. And barricade the entrance!",
    "For Rohan. For your people.",
    "Aragorn! Fall back to the Keep! Get your men out of there!",
    "There is one passage. It leads into the mountains. But they will not get far. The Uruk-hai are too many.",
    "The sun is rising.",
    "Look to my coming at first light on the fifth day. At dawn......Iook to the east.",
    "Yes!",
    "Yes.........Yes.........The horn of Helm Hammerhand......shall sound in the Deep......one last time.",
    "For death and glory.",
    "Gandalf.",
    "Theoden King stands alone.",
    "Brace the gate!",
    "Hold them!",
    "To the gate. Draw your swords!",
    "Make way! We cannot hold much longer!",
    "Hold them!",
    "How long do you need?",
    "Fell deeds, awake. Now for wrath......now for ruin and a red dawn.",
    "As long as you can give me.",
    "Let this be the hour when we draw swords together.",
    "Forth Eorlingas!",
    "Gimli!",
    "Timbers! Brace the gate!",
    "Come on. We can take them.",
    "Toss me.",
    "To the king!",
    "Yes!",
    "A hit. A fine hit.",
    "Break the dam! Release the river!",
    "Pippin! Hold on!",
    "Hold on, little Hobbits.",
    "What are you doing?",
    "Where are you going?",
    "It's a long way.",
    "What?",
    "I cannot jump the distance! You'll have to toss me!",
    "Don't tell the Elf.",
    "It's me. It's your Sam. Don't you know your Sam?",
    "Eomer.",
    "Not alone. Rohirrim!",
    "Shore up the door!",
    "Watch our backs!",
    "Throw another one over here!",
    "Higher!",
    "Hold fast the gate!",
    "Gimli! Aragorn! Get out of there!",
    "Aragorn!",
    "Follow me to the barricade.",
    "Make way!",
    "Fall back! Fall back!",
    "I can't do this, Sam.",
    "I know. It's all wrong. By rights, we shouldn't even be here. But we are. It's like in the great stories, Mr. Frodo. The ones that really mattered. Full of darkness and danger they were. And sometimes you didn't want to know the end.....because how could the end be happy? How could the world go back to the way it was...... when so much bad had happened?",
    "Victory! We have victory!",
    "Not a word.",
    "What are we holding on to, Sam?",
    "That there's some good in this world, Mr. Frodo. And it's worth fighting for.",
    "I think at last we understand one another, Frodo Baggins.",
    "You know the laws of our country, the laws of your father. If you let them go your life will be forfeit.",
    "Then it is forfeit. Release them.",
    "They have broken through! The castle is breached. Retreat!",
    "Folk in those stories......had lots of chances of turning back, only they didn't. They kept going......because they were holding on to something.",
    "But in the end, it's only a passing thing...... this shadow. Even darkness must pass. A new day will come. And when the sun shines, it will shine out the clearer. Those were the stories that stayed with you......that meant something. Even if you were too small to understand why. But I think, Mr. Frodo, I do understand. I know now.",
    "Retreat!",
    "Hurry! Inside. Get them inside!",
    "Into the Keep!",
    "Pull everybody back. Pull them back.",
    "Fall back!",
    "I will leave you at the western borders of the forest. You can make your way north to your homeland from there.",
    "That doesn't make sense to me. But then......you are very small. Perhaps you're right. South it is, then. Hold on, little Shirelings. I always like going south. Somehow it feels like going downhill.",
    "Are you mad? We'll be caught.",
    "No, we won't. Not this time.",
    "Look! Osgiliath burns!",
    "Mordor has come.",
    "The Ring will not save Gondor. It has only the power to destroy. Please......Iet me go.",
    "South? But that will lead you past lsengard.",
    "Yes. Exactly. If we go south, we can slip past Saruman unnoticed. The closer we are to danger, the farther we are from harm. It's the last thing he'll expect.",
    "Wait! Stop! Stop! Turn around. Turn around. Take us south.",
    "Hurry.",
    "Faramir! You must let me go!",
    "And those little family of field mice......that climb up sometimes, and they tickle me awfully.",
    "They had voices of their own.",
    "Saruman. A wizard should know better!",
    "There is no curse in Elvish......Entish or the tongues of Men......for this treachery.",
    "You could have picked a better spot.",
    "Well, lad, whatever luck you live by, let's hope it lasts the night.",
    "Your friends are with you, Aragorn.",
    "Let's hope they last the night.",
    "Many of these trees were my friends. Creatures I had known from nut and acorn.",
    "A Eruch'n, '-dano i faelas a hyn an uben tanatha le faelas!",
    "What's happening out there?",
    "I'm sorry, Treebeard.",
    "Shall I describe it to you? Or would you like me to find you a box?",
    "Look! The trees! They're moving!",
    "They're always trying to get somewhere where they....",
    "Yes!",
    "They have business with the Orcs. My business is with lsengard tonight......with rock and stone.",
    "So it begins.",
    "Tangado a chadad!",
    "Faeg i-varv d'n na lanc a nu ranc.",
    "Leithio i philinn!",
    "Did they hit anything?,",
    "Where are they going?",
    "Come, my friends. The Ents are going to war. It is likely......that we go to our doom. Last march......of the Ents.",
    "Give them a volley.",
    "Fire!",
    "Fire!",
    "Pendraith!",
    "Good!",
    "Swords! Swords!",
    "I'm on 17!",
    "Legolas! Two already!",
    "I'll have no pointy-ear outscoring me!",
    "Ribed bant!",
    "Send them to me! Come on!",
    "Nineteen!",
    "Merry.",
    "I have told your names to the Entmoot......and we have agreed......you are not Orcs.",
    "And what about Saruman? Have you come to a decision about him?",
    "Well, that's good news.",
    "We have just agreed.",
    "Yes?",
    "Now, don't be hasty, Master Meriadoc.",
    "War? Yes. It affects us all. Tree, root and twig. But you must understand, young Hobbit......it takes a long time......to say anything in Old Entish... ...and we never say anything......unless it is worth taking......a long time to say.",
    "Hasty? Our friends are out there. They need our help. They cannot fight this war on their own.",
    "Seventeen! Eighteen! Nineteen! Twenty! Twenty-one!",
    "Is this it? Is this is all you can conjure Saruman?",
    "Togo hon dad, Legolas!",
    "Brace the gate!",
    "Aragorn!",
    "Hold them! Stand firm!",
    "Gimli!",
    "Hado i philinn!",
    "Herio!",
    "Causeway!",
    "Dago hon! Dago hon!",
    "The Ents cannot hold back this storm. We must weather such things as we have always done.",
    "How can that be your decision?!",
    "You are young and brave, Master Merry. But your part in this tale is over. Go back to your home.",
    "Maybe Treebeard's right. We don't belong here, Merry. It's too big for us. What can we do in the end? We've got the Shire. Maybe we should go home.",
    "The fires of lsengard will spread......and the woods of Tuckborough and Buckland will burn. And.... And all that was once green and good in this world will be gone. There won't be a Shire, Pippin.",
    "Boromir! Boromir!",
    "This city was once the jewel of our kingdom. A place of light and beauty and music. And so it shall be once more!Let the armies of Mordor know this: Never again will the land of my people fall into enemy hands. This city of Osgiliath has been reclaimed,for Gondor!",
    "For Gondor!",
    "But you're part of this world! Aren't you?!",
    "This is not our war.",
    "For Gondor!",
    "You must help. Please. You must do something.",
    "For Gondor!",
    "Remember today, little brother. Today, life is good.",
    "What?",
    "He's here.",
    "One moment of peace, can he not give us that?",
    "Where is he? Where is Gondor's finest? Where's my first-born?",
    "Father!",
    "Leaves more time for drinking! Break out the ale! These men are thirsty!",
    "Good speech. Nice and short.",
    "They exaggerate. The victory belongs to Faramir also.",
    "Were you not entrusted to protect it?",
    "But for Faramir, this city would still be standing.",
    "Oh, too few. You let the enemy walk in and take it on a whim. Always you cast a poor reflection on me.",
    "I would have done, but our numbers were too few.",
    "That is not my intent.",
    "For Gondor!",
    "They say you vanquished the enemy almost single-handedly.",
    "You give him no credit, and yet he tries to do your will.",
    "lt has fallen into the hands of the Elves. Everyone will try to claim it: Men, Dwarves, wizards. We cannot let that happen. This thing must come to Gondor.",
    "Gondor.",
    "It's dangerous, I know. Ever the Ring will seek to corrupt the hearts of lesser Men. But you, you are strong. And our need is great. It is our blood which is being spilled, our people who are dying. Sauron is biding his time. He's massing fresh armies. He will return. And when he does, we will be powerless to stop him. You must go. Bring me back this mighty gift.",
    "No. My place is here with my people. Not in Rivendell.",
    "Would you deny your own father?",
    "He loves you, Father.",
    "lf there is need to go to Rivendell......send me in his stead.",
    "The One Ring. lsildur's Bane.",
    "Do not trouble me with Faramir......I know his uses, and they are few. We have more urgent things to speak of. Elrond of Rivendell has called a meeting. He will not say why, but I have guessed its purpose. It is rumored that the weapon of the enemy has been found.",
    "You? Oh, I see. A chance for Faramir, captain of Gondor, to show his quality. I think not. I trust this mission only to your brother. The one who will not fail me.",
    "Remember today, little brother.",
    "Captain Faramir!We found the third one.",
    "You must come with me. Now.",
    "Down there.",
    "To enter the Forbidden Pool bears the penalty of death. They wait for my command. Shall I shoot?",
    "The rock and pool Is nice and cool So juicy sweet Our only wish To catch a fish So juicy sweet",
    "Wait. This creature is bound to me. And I to him. He is our guide. Please......Iet me go down to him.",
    "Smeagol. Master is here. Come, Smeagol. Trust master. Come.",
    "We must go now?",
    "Don't hurt him!Smeagol, don't struggle. Smeagol, listen to me.",
    "Smeagol, you must trust master. Follow me. Come on. Come. Come, Smeagol. Nice Smeagol. That's it. Come on.",
    "Arwen. Tollen i l'. I chair gwannar na Valannor. Si bado, no c'rar.",
    "Brego.",
    "He is not coming back.Why do you linger herewhen there is no hope?",
    "May the grace of the Valarprotect you.",
    "Master!",
    "That's enough. Where are you leading them?,Answer me.",
    "Smeagol. Why does it cry, Smeagol?",
    "Cruel Men hurts us. Master tricksed us.",
    "Master betrayed us.",
    "No. Not its business. Leave us alone!",
    "Filthy little Hobbitses! They stole it from us!",
    "There is still hope.",
    "If Aragorn survives this waryou will still be parted.If Sauron is defeatedand Aragorn made king......and all that you hope forcomes true......you will still have to tastethe bitterness of mortality.",
    "Whether by the swordor the slow decay of time......Aragorn will die.And there will be no comfortfor you......no comfort to ease the painof his passing.He will come to death......an image of the splendorof the kings of Men......in glory undimmed beforethe breaking of the world.",
    "I have made my choice.",
    "Of course he did. I told you he was tricksy. I told you he was false.",
    "Master is our friend. Our friend.",
    "Arwen. There is nothing for you here......only death.",
    "I amar prestar aen... han mathon ne nen, han mathon ne chae a han noston ned 'wilith.",
    "What news?",
    "But you, my daughter......you will linger on in darknessand in doubt......as nightfall in winterthat comes without a star.Here you will dwell......bound to your griefunder the fading trees...... until all the world is changed......and the long years of your lifeare utterly spent.",
    "How many?",
    "Some thousands. More come every day.",
    "Who's covering the river to the north?",
    "We pulled 500 men at Osgiliath. If their city is attacked, we won't hold it.",
    "Gerich veleth n'n, ada.",
    "What did they steal?",
    "My precious!",
    "No. No.",
    "Our scouts report Saruman has attacked Rohan. Theoden's people have fled to Helm's Deep. But we must look to our own borders. Faramir, Orcs are on the move. Sauron is marshaling an army. Easterlings and Southrons are at the Black Gate.",
    "A im, '-'erin veleth l'n?",
    "We have to get out of here. You go. Go, now. You can do it. Use the Ring, Mr. Frodo. Just this once. Put it on. Disappear.",
    "No!",
    "Stop it! Leave him alone. Don't you understand? He's got to destroy it! That's where we're going, into Mordor. To the Mountain of Fire!",
    "Osgiliath is under attack. They call for reinforcements.",
    "Please. It's such a burden. Will you not help him?",
    "Captain?",
    "Prepare to leave. The Ring will go to Gondor.",
    "Mr. Frodo....",
    "So this is the answer to all the riddles. Here in the Wild I have you......two Halflings......and a host of men at my call. The Ring of Power within my grasp. A chance for Faramir, captain of Gondor......to show his quality.",
    "My men tell me that you are Orc spies.",
    "Saruman attacks from lsengard. Sauron from Mordor. The fight will come to Men on both fronts. Gondor is weak. Sauron will strike us soon. And he will strike hard. He knows now we do not have the strength to repel him.",
    "I can't. You were right, Sam. You tried to tell me but.... I'm sorry. The Ring's taking me, Sam. If I put it on......he'll find me. He'll see.",
    "Mae carnen, Brego, mellon n'n.",
    "We are Hobbits of the Shire. Frodo Baggins is my name, and this is Samwise Gamgee.",
    "Your bodyguard?",
    "His gardener.",
    "And where is your skulking friend? That gangrel creature. He had an ill-favored look.",
    "Well, if you're not spies, then who are you?",
    "There was no other. We set out from Rivendell with seven companions. One we lost in Moria......two were my kin......a Dwarf there was also. And an Elf and two Men. Aragorn, son of Arathorn, and Boromir of Gondor.",
    "You're a friend of Boromir?",
    "Speak.",
    "Spies? Now wait just a minute.",
    "Gimli, where is the king?",
    "Le abdollen. You look terrible.",
    "Hannon le.",
    "A great host, you say?",
    "All lsengard is emptied.",
    "How many?",
    "He's alive!",
    "Yes. For my part.",
    "Where is he? Where is he?,Get out of the way! I'm going to kill him!You are the luckiest, the canniest.....and the most reckless man I ever knew. Bless you, laddie.",
    "Ten thousand strong at least.",
    "Ten thousand?",
    "It is an army bred for a single purpose: To destroy the world of Men. They will be here by nightfall.",
    "I want every man and strong lad able to bear arms......to be ready for battle by nightfall.",
    "Dead? How? When?",
    "As one of his companions, I'd hoped you would tell me.",
    "If something has happened to Boromir, we would have you tell us.",
    "His horn washed up upon the riverbank, about six days past. It was cloven in two. But more than this, I know it in my heart. He was my brother.",
    "This is no rabble of mindless Orcs. These are Uruk-hai. Their armour is thick and their shields broad.",
    "I have fought many wars, Master Dwarf. I know how to defend my own keep.",
    "Let them come!",
    "They do not come to destroy Rohan's crops or villages. They come to destroy its people......down to the last child.",
    "We will cover the causeway and the gate from above. No army has ever breached the Deeping Wall......or set foot inside the Hornburg!",
    "It will grieve you then to learn that he is dead.",
    "They will break upon this fortress like water on rock. Saruman's hordes will pillage and burn. We've seen it before. Crops can be resown......homes rebuilt. Within these walls......we will outlast them.",
    "What would you have me do? Look at my men. Their courage hangs by a thread. If this is to be our end, then I would have them make such an end......as to be worthy of remembrance.",
    "And who will come? Elves? Dwarves? We are not so lucky in our friends as you. The old alliances are dead.",
    "Gondor will answer.",
    "We need more time to lay provisions--",
    "The light of the Evenstardoes not wax and wane.It is mine to give to whom I will.Like my heart.Go to sleep.",
    "I am asleep. This is a dream.",
    "Then it is a good dream. Sleep.",
    "( Gondor?! Where was Gondor when the Westfold fell?! Where was Gondor when our enemies closed in around us?! Where was Gon--?,No, my Lord Aragorn......we are alone. Get the women and children into the caves.",
    "Send out riders, my lord. You must call for aid.",
    "Minl' pendich nin i aur hen telitha.",
    "We wants it.We needs it.Must have the precious.They stole it from us.Sneaky little Hobbitses.Wicked. Tricksy. False.",
    "Yes, precious. False.They will cheat you, hurt you, lie!",
    "Master's my friend.",
    "Not listening. I'm not listening.",
    "You're a liar and a thief.",
    "No.",
    "We Ents have not troubled......about the wars of Men and wizards......for a very long time. But now, something is about to happen......that has not happened......for an age. Entmoot.",
    "There is no time. War is upon us. Secure the gate.",
    "No. Not master.",
    "You don't have any friends.Nobody likes you.",
    "What's that?",
    "'Tis a gathering.",
    "A gathering of what?",
    "Beech. Oak. Chestnut. Ash. Good. Good. Good. Many have come. Now we must decide if the Ents......will go to war.",
    "Arwen....",
    "Ae '-esteliach nad... estelio han. Estelio ammen.",
    "Where is she?The woman who gave you that jewel.",
    "Our time here is ending.Arwen's time is ending.Let her go.Let her take the ship into the west.Let her bear away her love for youto the Undying Lands.There it will be ever green.",
    "But never more than memory.",
    "I will not leave my daughter hereto die.",
    "Si peliannen i v'd na dail l'n. Si boe '-dhannathach.",
    "Dolen i v'd o nin.",
    "' i vethed... n' i onnad. Boe bedich go Frodo. Han b'd l'n.",
    "Ma nathach hi gwannathach or minuial archened?",
    "Murderer.",
    "Go away.",
    "Go away?",
    "I hate you.I hate you.",
    "Where would you be without me?Gollum. Gollum.I saved us.It was me. We survived because of me.",
    "She stays because she still has hope.",
    "She stays for you.She belongs with her people.",
    "Nach gwannatha sin?",
    "What did you say?",
    "Master looks after us now.We don't need you.",
    "What?",
    "No.",
    "Not anymore.",
    "Leave now......and never come back.",
    "Leave now and never come back.",
    "Leave now and never come back!",
    "Gandalf the White.Gandalf the Fool!Does he seek to humble mewith his newfound piety?",
    "The Ring of Barahir.So Gandalf Greyhamethinks he has found lsildur's heir.The lost king of Gondor.He is a fool.The line was broken years ago. It matters not.The world of Men shall fall.It will begin at Edoras.",
    "I am ready, Gamling.Bring my horse.",
    "This is not a defeat. We will return. We will return.",
    "'-ethelithon.",
    "Estelio guru l'n ne dagor. Ethelithach.",
    "You stink of horse.The Man......was he from Gondor?",
    "'-bedin o gurth ne dagor.",
    "There were threewho followed the wizard.An Elf, a Dwarf and a Man.",
    "No, from the North.One of the Dunedain RangersI thought he was.His cloth was poor.And yet he bore a strange ringTwo serpents with emerald eyes.. One devouringthe other crowned with golden flowers.",
    "O man pedich?",
    "Edra le men, men na guil edwen. Haer o auth a n'r a naeth.",
    "This belongs to you.",
    "It was a gift.Keep it.",
    "My lord?",
    "She is sailing to the Undying Landswith all that is left of her kin.",
    "What is it? Hama?",
    "I'm not sure.",
    "I am mortal. You are Elf-kind.It was a dream, Arwen.Nothing more.",
    "I don't believe you.",
    "A scout!",
    "Wargs!",
    "Look.Look. See what Smeagol finds?",
    "They are young.They are tender. They are nice.Yes, they are. Eat them. Eat them!",
    "You'll make him sick, you will......behaving like that. There's only one way to eata brace of coneys.",
    "We told him to go away.And away he goes, precious. Gone! Gone! Gone!Smeagol is free!",
    "Why are you saying this?",
    "What's to ruin? There's hardly any meaton them.",
    "Po-ta-toes.",
    "Boil them, mash themstick them in a stew.Lovely, big, golden chipswith a nice piece of fried fish.",
    "Even you couldn't say no to that.",
    "What's it doing?Stupid, fat Hobbit.It ruins it.",
    "You're hopeless.",
    "Mr. Frodo?",
    "Who are they?",
    "What's taters, precious?What's taters? Eh?",
    "What we need is a few good taters.",
    "You have some skill with a blade.",
    "Oh, yes, we could.Spoil a nice fish. Give it to us raw... ...and wriggling.You keep nasty chips.",
    "Women of this country learned long ago:Those without swordscan still die upon them.I fear neither death nor pain.",
    "A cage.To stay behind bars until useand old age accept them.And all chance of valor has gonebeyond recall or desire.",
    "What do you fear, my lady?",
    "Send out your Warg-riders.",
    "Theoden will not stay at Edoras.It's vulnerable. He knows this. He will expect an attack on the city. They will flee to Helm's Deep......the great fortress of Rohan. It is a dangerous road to takethrough the mountains. They will be slow. They will have women and childrenwith them.",
    "What?",
    "Call him names.Run him down all the time.",
    "Because.Because that's what he is, Mr. Frodo.There's naught left in himbut lies and deceit.It's the Ring he wants.It's all he cares about.",
    "Why do you do that?",
    "You have no idea what it did to him......what it's still doing to him. I want to help him, Sam.",
    "You're a daughter of kings......a shieldmaiden of Rohan.I do not think that would be your fate.",
    "Why?",
    "Get them out of here!",
    "All riders to the head of the column.",
    "What is it? What do you see?",
    "Warg! We're under attack!",
    "You must lead the peopleto Helm's Deep, and make haste.",
    "Come on. Get me up here. I'm a rider.Come on!",
    "No!You must do this, for me.",
    "I can fight.",
    "Hey, stinker, don't go gettingtoo far ahead.",
    "Forward. I mean, charge forward.",
    "Stay together!",
    "Bring your pretty face to my axe.",
    "Follow me!",
    "That's it! Go on!",
    "Make for the lower ground!",
    "Ready to do what?",
    "To make his war.The last war that will coverall the world in Shadow.",
    "Mr. Frodo.Look.It's an oliphaunt.",
    "We've got to get moving. Come on, Sam.",
    "Wicked Men.Servants of Sauron.They are called to Mordor.The Dark One is gathering all armiesto him.It won't be long now.He will soon be ready.",
    "No one at home will believe this.",
    "Smeagol?",
    "We've lingered here too long.Come on, Sam.",
    "Wait! We're innocent travelers!",
    "We are bound to an errand of secrecy.Those that claim to oppose the enemywould do well not to hinder us.",
    "The enemy?,His sense of duty was no lessthan yours, I deem. You wonder what his name is......where he came from. And if he was really evil at heart. What lies or threats led himon this long march from home. If he would not rather have stayed there......in peace. War will make corpses of us all. Bind their hands.",
    "There are no travelers in this land.Only servants of the Dark Tower.",
    "Because I have to believehe can come back.",
    "You can't save him, Mr. Frodo.",
    "It's true, you don't seemany Dwarf women.And in fact, they are so alikein voice and appearance......that they're often mistakenfor Dwarf men.",
    "What do you know about it?Nothing!I'm sorry, Sam. I don't knowwhy I said that.",
    "I do. It's the Ring.You can't take your eyes off it.I've seen you.You're not eating. You barely sleep. It's taken hold of you, Mr. Frodo. You have to fight it.",
    "I know what I have to do, Sam.The Ring was entrusted to me.It's my task.Mine! My own!",
    "Can't you hear yourself?Don't you know who you sound like?",
    "Aragorn!",
    "That one counts as mine!Stinking creature.",
    "You lie.",
    "Tell me what happenedand I will ease your passing.",
    "Aragorn?",
    "Get the wounded on horses.The wolves of lsengard will return.Leave the dead.",
  ],

  EXPECTED_CHARACTERS: [
    "Adanel",
    "Adrahil I",
    "Adrahil II",
    "Aegnor",
    "Aerin",
    "Ailinel",
    "Aglahad",
    "Algund",
    "Almiel",
    "Alphros",
    "Almarian",
    "Amandil",
    "Amarië",
    "Aldor",
    "Aldamir",
    "Amlaith",
    "Amroth",
    "Amrothos",
    "Anairë",
    "Anardil",
    "Anborn",
    "Andreth",
    "Andróg",
    "Amras",
    "Angamaitë",
    "Amdír",
    "Amrod",
    "Annael",
    "Angbor",
    "Angelimir",
    "Angrod",
    "Anárion",
    "Ar-Adûnakhôr",
    "Ar-Gimilzôr",
    "Ar-Zimrathôn",
    "Ar-Pharazôn",
    "Ar-Sakalthôr",
    "Arador",
    "Araglas",
    "Aragorn I",
    "Aragorn II Elessar",
    "Aragost",
    "Arahad I",
    "Arahad II",
    "Arahael",
    "Aranarth",
    "Arantar",
    "Aranuir",
    "Aranwë",
    "Araphant",
    "Arathorn I",
    "Arathorn II",
    "Araval",
    "Aravir",
    "Aravorn",
    "Arciryas",
    "Arassuil",
    "Araphor",
    "Aratan",
    "Ardamir (son of Axantur)",
    "Aredhel",
    "Argeleb I",
    "Arminas",
    "Arthad",
    "Arvedui",
    "Arvegil",
    "Arveleg I",
    "Arveleg II",
    "Argon",
    "Argonui",
    "Argeleb II",
    "Atanatar II",
    "Atanalcar",
    "Arwen",
    "Azaghâl",
    "Aulendil (Vardamir's son)",
    "Angelica Baggins",
    "Axantur",
    "Balbo Baggins",
    "Atanatar I",
    "Belladonna (Took) Baggins",
    "Berylla (Boffin) Baggins",
    "Bungo Baggins",
    "Dudo Baggins",
    "Laura (Grubb) Baggins",
    "Fosco Baggins",
    "Drogo Baggins",
    "Frodo Baggins",
    "Longo Baggins",
    "Mungo Baggins",
    "Peony (Baggins) Burrows",
    "Ponto Baggins",
    "Ponto Baggins II",
    "Balin",
    "Baragund",
    "Porto Baggins",
    "Baran",
    "Bain",
    "Baranor (Gondor)",
    "Bard",
    "Bard II",
    "Beldir",
    "Beldis",
    "Barahir",
    "Belecthor I",
    "Beleg of Arnor",
    "Belegorn",
    "Belegund",
    "Belemir",
    "Belen",
    "Beorn",
    "Bereg",
    "Beregond",
    "Beregond (Captain)",
    "Berelach",
    "Beren",
    "Baranor",
    "Beren (Steward)",
    "Beren (Belemir's son)",
    "Bergil",
    "Barahir (Steward)",
    "Bifur",
    "Bilbo Baggins",
    "Bladorthin",
    "Black Serpent",
    "Blanco",
    "Belecthor II",
    "Bob",
    "Donnamira (Took) Boffin",
    "Daisy (Baggins) Boffin",
    "Bosco Boffin",
    "Folco Boffin",
    "Gerda (Boffin) Bolger",
    "Griffo Boffin",
    "Hugo Boffin",
    "Ivy (Goodenough) Boffin",
    "Basso Boffin",
    "Otto Boffin",
    "Rollo Boffin",
    "Tosto Boffin",
    "Vigo Boffin",
    "Druda Burrows Boffin",
    "Filibert Bolger",
    "Fredegar Bolger",
    "Jessamine (Boffin) Bolger",
    "Bofur",
    "Odovacar Bolger",
    "Rosamunda (Took) Bolger",
    "Jago Boffin",
    "Buffo Boffin",
    "Bombur",
    "Borlad",
    "Borlas",
    "Boromir",
    "Boromir (House of Bëor)",
    "Boromir (Steward)",
    "Wilibald Bolger",
    "Borondir",
    "Borthand",
    "Blanco Bracegirdle",
    "Bruno Bracegirdle",
    "Primrose Bracegirdle",
    "Brand",
    "Brandir",
    "Adaldrida (Bolger) Brandybuck",
    "Amaranth Brandybuck",
    "Borlach",
    "Esmeralda Brandybuck",
    "Estella (Bolger) Brandybuck",
    "Hilda Brandybuck",
    "Madoc Brandybuck",
    "Melilot Brandybuck",
    "Mentha Brandybuck",
    "Borin",
    "Mirabella (Took) Brandybuck",
    "Primula (Brandybuck) Baggins",
    "Seredic Brandybuck",
    "Brego",
    "Bregolas",
    "Bregor",
    "Sapphira (Brockhouse) Boffin",
    "Bucca of the Marish",
    "Asphodel (Brandybuck) Burrows",
    "Milo Burrows",
    "Celandine Brandybuck",
    "Bëor",
    "Bór",
    "Calimehtar",
    "Minto Burrows",
    "Boron",
    "Meriadoc Brandybuck",
    "Calmacil",
    "Celeborn",
    "Celebrimbor",
    "Celebrindor",
    "Celebrían",
    "Celegorm",
    "Celepharn",
    "Cemendur",
    "Cemendur (son of Axantur)",
    "Ceorl",
    "Caliondo",
    "Cirion",
    "Ciryandil",
    "Ciryatur",
    "Ciryon",
    "Bowman Cotton",
    "Lily Cotton",
    "Marigold (Gamgee) Cotton",
    "Rosie Cotton",
    "Tolman Cotton",
    "Castamir the Usurper",
    "Curufin",
    "Círdan",
    "Dairuin",
    "Damrod",
    "User:Deathshriek",
    "Denethor (First Age)",
    "Falco Chubb-Baggins",
    "Caranthir",
    "Denethor II",
    "Diamond Took",
    "Dinodas Brandybuck",
    "Dior (Steward)",
    "Dodinas Brandybuck",
    "Dori",
    "Dorlas",
    "Denethor I",
    "Duinhir",
    "Durin VII",
    "Dwalin",
    "Dáin I",
    "Dervorin",
    "Déagol",
    "Déor",
    "Derufin",
    "Duilin",
    "Dáin II Ironfoot",
    "Déorwine",
    "Dírhael",
    "Dírhavel",
    "Dís",
    "Dúnhere",
    "Ecthelion II",
    "Ecthelion I",
    "Edrahil",
    "Egalmoth",
    "Eglantine (Banks) Took",
    "Eilinel",
    "Elatan",
    "Eldacar (King of Arnor)",
    "Eldarion",
    "Eldacar (King of Gondor)",
    "Elemmírë (elf)",
    "Elendil",
    "Elendur",
    "Elendur of Arnor",
    "Elboron",
    "Eldalótë",
    "Elenwë",
    "Elfhelm",
    "Elfhild",
    "Elfwine",
    "Elladan and Elrohir",
    "Emeldir",
    "Elphir",
    "Elrond",
    "Enel",
    "Enelyë",
    "Enerdhil",
    "Erchirion",
    "Erellont",
    "Erendis",
    "Erestor",
    "Eorl the Young",
    "Erkenbrand",
    "Estelmo",
    "Eradan",
    "Eärendur of Númenor",
    "Eärnil I",
    "Eärnil II",
    "Eärnur",
    "Eärwen",
    "Eärendur (Lord of Andúnië)",
    "Eöl",
    "Eärendil of Gondor",
    "Eärendur of Arnor",
    "Faramir (son of Ondoher)",
    "Fastred",
    "Fastred (Pelennor Fields)",
    "Fengel",
    "Ferumbras Took II",
    "Finarfin",
    "Findegil",
    "Findis",
    "Finduilas",
    "Finduilas of Dol Amroth",
    "Fingolfin",
    "Farin",
    "Fingon",
    "Finrod",
    "Finwë",
    "Flói",
    "Faramir",
    "Folca",
    "Fastolph Bolger",
    "Folcred",
    "Forlong",
    "Folcwine",
    "Fortinbras Took I",
    "Forthwini",
    "Forweg",
    "Freca",
    "Fram",
    "Frerin",
    "Frumgar",
    "Fréawine",
    "Frór",
    "Frár",
    "Fundin",
    "Fréa",
    "Fréaláf Hildeson",
    "Fëanor",
    "Fíriel",
    "Fíli and Kíli",
    "Galar",
    "Galadriel",
    "Galdor",
    "Galion",
    "Daisy Gamgee I",
    "Frodo Gardner",
    "Hamson Gamgee",
    "May Gamgee",
    "Samwise Gamgee",
    "Gamling",
    "Elanor Gardner",
    "Gelmir",
    "Hamfast Gamgee",
    "Halfred Gamgee",
    "Galdor of the Havens",
    "Gil-galad",
    "Gildis",
    "Gildor (Edain)",
    "Gildor Inglorion",
    "Gilfanon",
    "Ghân-buri-Ghân",
    "Gethron",
    "Gilraen",
    "Gelmir (of Angrod's kin)",
    "Girion",
    "Gimilzagar",
    "Glorfindel",
    "Glirhuin",
    "Gléowine",
    "Gimilkhâd",
    "Gimli",
    "Golasgil",
    "Goldwine",
    "Hanna (Goldworthy) Brandybuck",
    "Gorbulas Brandybuck",
    "Gorhendad (Oldbuck) Brandybuck",
    "Gorlim",
    "Glóin (King of Durin's Folk)",
    "Glóin",
    "Glóredhel",
    "Gormadoc Deepdelver Brandybuck",
    "Gram",
    "Holman Greenhand",
    "Rose Greenhand",
    "Grimbeorn",
    "Grimbold",
    "Grithnir",
    "Gróin",
    "Halfred Greenhand",
    "Erling Greenhand",
    "Guilin",
    "Hending Greenhand",
    "Grór",
    "Gundor",
    "Guthláf",
    "Hador",
    "Hador (Steward)",
    "Halbarad",
    "Haldir (Haladin)",
    "Gálmód",
    "Gwindor",
    "Haldir (Lorien)",
    "Haleth",
    "Gárulf",
    "Haleth (Helm's son)",
    "Hallacar",
    "Hallas (Steward)",
    "Halmir",
    "Hallatan",
    "Hamfast of Gamwich",
    "Hareth",
    "Harding",
    "Hardang",
    "Hathaldir",
    "Hatholdir",
    "Helm Hammerhand",
    "Hathol",
    "Handir",
    "Henderch",
    "Herefara",
    "Hendor",
    "Herion",
    "Herubrand",
    "Herucalmo",
    "Hirgon",
    "Hirluin",
    "Hob Gammidge",
    "Hob Hayward",
    "Tobias Hornblower",
    "Holfast Gardner",
    "Horn",
    "Hundad",
    "Hundar",
    "Hunthor",
    "Huor",
    "Hyarmendacil I",
    "Hyarmendacil II",
    "Háma",
    "Húrin II",
    "Háma (Helm's son)",
    "Húrin of Emyn Arnen",
    "Húrin",
    "Imin",
    "Iminyë",
    "Imlach",
    "Imrahil",
    "Imrazôr",
    "Idril",
    "Ibûn",
    "Indis",
    "Húrin I",
    "Ingwë",
    "Inzilbêth",
    "Ioreth",
    "Iorlas",
    "Isembold Took",
    "Ingold",
    "Isengrim Took III",
    "Indor",
    "Ingwion",
    "Isilmo",
    "Ivriniel",
    "Lalaith",
    "Larnach",
    "Legolas",
    "Isildur",
    "Lindir",
    "Lindissë",
    "Isilmë",
    "Lindo",
    "Ivorwen",
    "Lindórië",
    "Lenwë",
    "Lorgan",
    "Lothíriel",
    "Léod",
    "Brytta Léofa",
    "Lóni",
    "Lúthien",
    "Farmer Maggot",
    "Mablung the Ranger",
    "Maglor",
    "Maedhros",
    "Mahtan",
    "Magor",
    "Mairen",
    "Malach",
    "Maeglin",
    "Malvegil",
    "Manthor",
    "Manwendil",
    "Malva Headstrong Brandybuck",
    "Mallor",
    "Marach",
    "Marcho",
    "Mardil Voronwë",
    "Malbeth the Seer",
    "Marhwini",
    "Marmadas Brandybuck",
    "Master of Laketown",
    "Meneldil",
    "Meleth",
    "Meril-i-Turinqi",
    "Merimas Brandybuck",
    "Minohtar",
    "Marroc Brandybuck",
    "Marhari",
    "Minardil",
    "Mithrellas",
    "Morwen",
    "Morwen (Gondor)",
    "Morwë",
    "Míriel",
    "Mîm",
    "Narmacil I",
    "Nessanië",
    "Nimrodel",
    "Nerdanel",
    "Naugladur",
    "Nina Lightfoot",
    "Nolondil",
    "Niënor",
    "Nob",
    "Narmacil II",
    "Náin I",
    "Náin II",
    "Náli",
    "Nár",
    "Númendil",
    "Núneth",
    "Nurwë",
    "Nori",
    "Náin (father of Dáin II Ironfoot)",
    "Old Noakes",
    "Olwë",
    "Orchaldor",
    "Ondoher",
    "Ori",
    "Orodreth",
    "Orodreth (Steward)",
    "Oromendil",
    "Ohtar",
    "Ostoher",
    "Orophin",
    "Pelendur",
    "Mrs. Proudfoot",
    "Pengolodh",
    "Otho Sackville-Baggins",
    "Odo Proudfoot",
    "Radhruin",
    "Oropher",
    "Ragnir",
    "Ragnor",
    "Rían",
    "Rían (Gondor)",
    "Rowan Greenhand",
    "Rudigar Bolger",
    "Rufus Burrows",
    "Rómendacil I",
    "Lobelia Sackville-Baggins",
    "Rúmil (Noldo)",
    "Lotho Sackville-Baggins",
    "Sadoc Brandybuck",
    "Sador",
    "Saelon",
    "Rúmil of Lórien",
    "Sagroth",
    "Rómendacil II",
    "Silmariën",
    "Sangahyando",
    "Siriondil",
    "Saradas Brandybuck",
    "Robin Smallburrow",
    "Soronto",
    "Morwen Steelsheen",
    "Tar-Alcarin",
    "Ted Sandyman",
    "Tar-Aldarion",
    "Tar-Amandil",
    "Tar-Ancalimon",
    "Tar-Anárion",
    "Tar-Ardamin",
    "Tar-Atanamir",
    "Tar-Calmacil",
    "Tar-Ciryatan",
    "Tar-Elendil",
    "Tar-Ancalimë",
    "Tar-Palantir",
    "Tar-Súrion",
    "Tar-Minastir",
    "Tar-Míriel",
    "Tar-Telperiën",
    "Tar-Vanimeldë",
    "Tarannon Falastur",
    "Tar-Telemmaitë",
    "Tarcil",
    "Tar-Meneldur",
    "Targon",
    "Tata",
    "Tatië",
    "Tarciryan",
    "Telchar",
    "Telemnar",
    "Telumehtar",
    "The King of the Dead",
    "Tarondor",
    "Tarondor of Arnor",
    "User:Technobliterator/Showcase",
    "Thengel",
    "Thorondir",
    "Thranduil",
    "Thráin I",
    "Thorin II Oakenshield",
    "Thráin II",
    "Thorin III Stonehelm",
    "Thrór",
    "Théoden",
    "Théodred",
    "Tindómiel",
    "Thorin I",
    "Faramir Took I",
    "Isumbras Took I",
    "Fortinbras Took II",
    "Isumbras Took III",
    "Adalgrim Took",
    "Adamanta (Chubb) Took",
    "Isengrim Took II",
    "Adelard Took",
    "Ferumbras III Took",
    "Bandobras Took",
    "Hildifons Took",
    "Isembard Took",
    "Hildigrim Took",
    "Gerontius Took",
    "Hildibrand Took",
    "Paladin Took II",
    "Pearl Took",
    "Peregrin Took",
    "Rosa (Baggins) Took",
    "Sigismond Took",
    "Turgon",
    "Turgon (Steward)",
    "Túrin",
    "Tulkastor",
    "Tuor",
    "Turambar",
    "Uldor",
    "Túrin II",
    "Ulfang",
    "Ulfast",
    "Ulbar",
    "Túrin I",
    "Urthel",
    "Ulwarth",
    "Vairë (Elf)",
    "Valacar",
    "Valandil",
    "Valandur",
    "Valandil of Andúnië",
    "Vidugavia",
    "Vardamir Nólimon",
    "Vardilmë",
    "Vidumavi",
    "Vorondil",
    "Voronwë",
    "Vëantur",
    "Walda",
    "Willie Banks",
    "Wiseman Gamwich",
    "Wulf I",
    "Wídfara",
    "Írimë",
    "Óin",
    "Yávien",
    "Dora Baggins",
    "Largo Baggins",
    "Mimosa (Bunce) Baggins",
    "Pansy Baggins",
    "Polo Baggins",
    "Ponto Baggins I",
    "Bingo Baggins",
    "Chica (Chubb) Baggins",
    "Óin (King of Durin's Folk)",
    "Prisca (Baggins) Bolger",
    "Rudibert Bolger",
    "Theobald Bolger",
    "Adalgar Bolger",
    "Ruby (Bolger) Baggins",
    "Wilimar Bolger",
    "Camellia (Sackville) Baggins",
    "Everard Took",
    "Gundahar Bolger",
    "Ferdinand Took",
    "Pervinca Took",
    "Pimpernel Took",
    "Ferdibrand Took",
    "Reginard Took",
    "Flambard Took",
    "Lalia (Clayhanger) Took",
    "Ruby Gamgee",
    "Rudolph Bolger",
    "Tanta (Hornblower) Baggins",
    "Inigo Baggins",
    "Tanta Hornblower",
    "Tobold Hornblower",
    "Lily (Baggins) Goodbody",
    "Togo Goodbody",
    "Goldberry",
    "Bell (Goodchild) Gamgee",
    "Goldilocks (Gardner) Took",
    "Merry Gamgee",
    "Bilbo Gamgee",
    "Halfast Gamgee",
    "Rose Gamgee",
    "Pippin Gamgee",
    "Durin",
    "Poppy (Chubb-Baggins) Bolger",
    "Robin Gardner",
    "Primrose Gardner",
    "Hamfast Gardner",
    "Tolman Cotton Jr.",
    "Carl Cotton",
    "Wilcome Cotton",
    "Doderic Brandybuck",
    "Daisy Gamgee",
    "Berilac Brandybuck",
    "Gorbadoc Brandybuck",
    "Marmadoc Brandybuck",
    "Ilberic Brandybuck",
    "Orgulas Brandybuck",
    "Rorimac Brandybuck",
    "Merimac Brandybuck",
    "Salvia (Brandybuck) Bolger",
    "Bilbo Gardner",
    "Briffo Boffin",
    "Gruffo Boffin",
    "Lavender (Grubb) Boffin",
    "Uffo Boffin",
    "Bodo Proudfoot",
    "Sancho Proudfoot",
    "Olo Proudfoot",
    "Saradoc Brandybuck",
    "Nimloth (elf)",
    "Linda (Baggins) Proudfoot",
    "Gríma Wormtongue",
    "Gollum",
    "Legolas (elf of Gondolin)",
    "Gandalf",
    "Radagast",
    "Tilion",
    "Elemmakil",
    "Saruman",
    "Sauron",
    "Eönwë",
    "Durin's Bane",
    "Alatar",
    "Arien",
    "Uinen",
    "Mosco Burrows",
    "Myrtle Burrows",
    "Pallando",
    "Moro Burrows",
    "Thingol",
    "Théodwyn",
    "Eärendil",
    "Harry Goatleaf",
    "Treebeard",
    "Witch-King of Angmar",
    "Mouth of Sauron",
    "Irolas",
    "Lagduf",
    "Fire-drake of Gondolin",
    "Angrim",
    "Angelimar",
    "Penlod",
    "Squint-eyed Southerner",
    "Fimbrethil",
    "Bill Ferny",
    "Fastred of Greenholm",
    "Falathar",
    "Elfstan Fairbairn",
    "Snaga (Two Towers orc)",
    "Snaga",
    "Smaug",
    "Seers",
    "Shelob",
    "Shagrat",
    "Scatha",
    "Salmar",
    "Sandyman",
    "Salgant",
    "Saeros",
    "Ruffian Leader",
    "Roäc",
    "Andwise Roper",
    "Rog",
    "River-woman",
    "Radbug",
    "Khîm",
    "Khamûl",
    "Irmo",
    "Eru Ilúvatar",
    "Ilmarë",
    "Hurin (Warden of the Keys)",
    "Huan",
    "Estë",
    "Éowyn",
    "Éomer",
    "Elwing",
    "Eluréd and Elurín",
    "Elros",
    "Elmo",
    "Egalmoth (elf)",
    "Ecthelion of the Fountain",
    "Ebor",
    "Ossë",
    "Oromë",
    "Orleg",
    "Orcobal",
    "Old Man Willow",
    "Hild",
    "Herumor (Fourth Age)",
    "Herumor",
    "Mat Heathertoes",
    "Haldar",
    "Haldad",
    "Draugluin",
    "Dior",
    "Dina Diggle",
    "Daeron",
    "Óin (King of Durin's Folk)",
    "Óin",
    "mar",
    "bal",
    "Írimë",
    "Írildë",
    "Éothain",
    "Éomund",
    "Éofor",
    "Zamîn",
    "Yavanna",
    "Tom Bombadil",
    "Bolg",
    "Boldog (Character)",
    "Bodruith",
    "Berúthiel",
    "Nienna",
    "Nielíqui",
    "Nessa",
    "Nellas",
    "Nauglath",
    "Narvi",
    "Nahar",
    "Mûmakil",
    "Muzgash",
    "The Moth",
    "Minastan",
    "Meneldor",
    "Men",
    "Melkor",
    "Melian",
    "Mauhúr",
    "Manwë",
    "Mandos",
    "Gwaihir",
    "Grishnákh",
    "Great Goblin",
    "Gothmog (Lieutenant of Morgul)",
    "Gothmog",
    "Gostir",
    'Gormadoc "Deepdelver" Brandybuck',
    "Gorgol",
    "Gorbag",
    "Golfimbul",
    "Glaurung",
    "Gimli (Elf)",
    "Gilmith",
    "Cottar",
    "Cora Goodbody",
    "Carcharoth",
    "Carc",
    "Calimmacil",
    "Barliman Butterbur",
    "Witch-king of Angmar",
    "Wife of Barach",
    "Widow Rumble",
    "Will Whitfoot",
    "Watcher in the Water",
    "Warg Matriarch",
    "Vëannë",
    "Varda",
    "Vairë",
    "Ungoliant",
    "Ulrad",
    "Ulmo",
    "Uglúk",
    "Ufthak",
    "Daddy Twofoot",
    "Tulkas",
    "Beleg",
    "Beechbone",
    "Barahir (Fourth Age)",
    "Baldor",
    "Balcmeg",
    "Man in the Moon",
    'Malva "Headstrong" Brandybuck',
    "Malantur",
    "Mallor (BOH)",
    "Mablung",
    "Lungorthin",
    "Lugdush",
    "Letter 211",
    "Landroval",
    "Gamil Zirak",
    "Galdor of the Tree",
    "Galathil",
    "Galador",
    "Fíriel Fairbairn",
    "Fuithluin",
    "Fuinur",
    "Fladrif",
    "Broncho Stonecrow",
    "Brodda",
    "Bregalad",
    "Tolman Gardner",
    "Tom, Bert, and William",
    "Tim",
    "Thuringwethil",
    "Thorondor",
    "Azog",
    "Aulë",
    "Asgon",
    "Artamir",
    "Ancalagon",
    "Andvír",
    "Amlach",
    "Aghan",
    "Agathor",
    "Aerandir",
    "Freda",
    "Sharku",
    "Madril",
    "Gothmog",
    "Morwen",
    "Figwit",
    "MINOR_CHARACTER",
    "MINOR_CHARACTER",
    "Éothain",
  ],

  EXPECTED_CHAPTERS: [
    "A Long-expected Party",
    "The Shadow of the Past",
    "Three is Company",
    "A Short Cut to Mushrooms",
    "A Conspiracy Unmasked",
    "The Old Forest",
    "In the House of Tom Bombadil",
    "Fog on the Barrow-Downs",
    "At the Sign of The Prancing Pony",
    "Strider",
    "A Knife in the Dark",
    "Flight to the Ford",
    "Many Meetings",
    "The Council of Elrond",
    "The Ring Goes South",
    "A Journey in the Dark",
    "The Bridge of Khazad-dûm",
    "Lothlórien",
    "The Mirror of Galadriel",
    "Farewell to Lórien",
    "The Great River",
    "The Breaking of the Fellowship",
    "The Departure of Boromir",
    "The Riders of Rohan",
    "The Uruk-Hai",
    "Treebeard",
    "The White Rider",
    "The King of the Golden Hall",
    "Helm's Deep",
    "The Road to Isengard",
    "Flotsam and Jetsam",
    "The Voice of Saruman",
    "The Palantir",
    "The Taming of Smeagol",
    "The Passage of the Marshes",
    "The Black Gate is Closed",
    "Of Herbs and Stewed Rabbit",
    "The Window on the West",
    "The Forbidden Pool",
    "Journey to the Cross-roads",
    "The Stairs of Cirith Ungol",
    "Shelob's Lair",
    "The Choices of Master Samwise",
    "Minas Tirith",
    "The Passing of the Grey Company",
    "The Muster of Rohan",
    "The Siege of Gondor",
    "The Ride of the Rohirrim",
    "The Battle of the Pelennor Fields",
    "The Pyre of Denethor",
    "The Houses of Healing",
    "The Last Debate",
    "The Black Gate Opens",
    "The Tower of Cirith Ungol",
    "The Land of Shadow",
    "Mount Doom",
    "The Field of Cormallen",
    "The Steward and the King",
    "Many Partings",
    "Homeward Bound",
    "The Scouring of the Shire",
    "The Grey Havens",
  ],
};
