module.exports = {
  EXPECTED_BOOKS: [
    "The Fellowship Of The Ring",
    "The Two Towers",
    "The Return Of The King",
  ],

  EXPECTED_MOVIES: [
    "The Lord of the Rings Series",
    "The Hobbit Series",
    "The Unexpected Journey",
    "The Desolation of Smaug",
    "The Battle of the Five Armies",
    "The Two Towers ",
    "The Fellowship of the Ring",
    "The Return of the King",
  ],

  EXPECTED_CHARACTERS: [
    "Adanel",
    "Adrahil I",
    "Adrahil II",
    "Aegnor",
    "Aerin",
    "Ailinel",
    "Aglahad",
    "Algund",
    "Almiel",
    "Alphros",
    "Almarian",
    "Amandil",
    "Amarië",
    "Aldor",
    "Aldamir",
    "Amlaith",
    "Amroth",
    "Amrothos",
    "Anairë",
    "Anardil",
    "Anborn",
    "Andreth",
    "Andróg",
    "Amras",
    "Angamaitë",
    "Amdír",
    "Amrod",
    "Annael",
    "Angbor",
    "Angelimir",
    "Angrod",
    "Anárion",
    "Ar-Adûnakhôr",
    "Ar-Gimilzôr",
    "Ar-Zimrathôn",
    "Ar-Pharazôn",
    "Ar-Sakalthôr",
    "Arador",
    "Araglas",
    "Aragorn I",
    "Aragorn II Elessar",
    "Aragost",
    "Arahad I",
    "Arahad II",
    "Arahael",
    "Aranarth",
    "Arantar",
    "Aranuir",
    "Aranwë",
    "Araphant",
    "Arathorn I",
    "Arathorn II",
    "Araval",
    "Aravir",
    "Aravorn",
    "Arciryas",
    "Arassuil",
    "Araphor",
    "Aratan",
    "Ardamir (son of Axantur)",
    "Aredhel",
    "Argeleb I",
    "Arminas",
    "Arthad",
    "Arvedui",
    "Arvegil",
    "Arveleg I",
    "Arveleg II",
    "Argon",
    "Argonui",
    "Argeleb II",
    "Atanatar II",
    "Atanalcar",
    "Arwen",
    "Azaghâl",
    "Aulendil (Vardamir's son)",
    "Angelica Baggins",
    "Axantur",
    "Balbo Baggins",
    "Atanatar I",
    "Belladonna (Took) Baggins",
    "Berylla (Boffin) Baggins",
    "Bungo Baggins",
    "Dudo Baggins",
    "Laura (Grubb) Baggins",
    "Fosco Baggins",
    "Drogo Baggins",
    "Frodo Baggins",
    "Longo Baggins",
    "Mungo Baggins",
    "Peony (Baggins) Burrows",
    "Ponto Baggins",
    "Ponto Baggins II",
    "Balin",
    "Baragund",
    "Porto Baggins",
    "Baran",
    "Bain",
    "Baranor (Gondor)",
    "Bard",
    "Bard II",
    "Beldir",
    "Beldis",
    "Barahir",
    "Belecthor I",
    "Beleg of Arnor",
    "Belegorn",
    "Belegund",
    "Belemir",
    "Belen",
    "Beorn",
    "Bereg",
    "Beregond",
    "Beregond (Captain)",
    "Berelach",
    "Beren",
    "Baranor",
    "Beren (Steward)",
    "Beren (Belemir's son)",
    "Bergil",
    "Barahir (Steward)",
    "Bifur",
    "Bilbo Baggins",
    "Bladorthin",
    "Black Serpent",
    "Blanco",
    "Belecthor II",
    "Bob",
    "Donnamira (Took) Boffin",
    "Daisy (Baggins) Boffin",
    "Bosco Boffin",
    "Folco Boffin",
    "Gerda (Boffin) Bolger",
    "Griffo Boffin",
    "Hugo Boffin",
    "Ivy (Goodenough) Boffin",
    "Basso Boffin",
    "Otto Boffin",
    "Rollo Boffin",
    "Tosto Boffin",
    "Vigo Boffin",
    "Druda Burrows Boffin",
    "Filibert Bolger",
    "Fredegar Bolger",
    "Jessamine (Boffin) Bolger",
    "Bofur",
    "Odovacar Bolger",
    "Rosamunda (Took) Bolger",
    "Jago Boffin",
    "Buffo Boffin",
    "Bombur",
    "Borlad",
    "Borlas",
    "Boromir",
    "Boromir (House of Bëor)",
    "Boromir (Steward)",
    "Wilibald Bolger",
    "Borondir",
    "Borthand",
    "Blanco Bracegirdle",
    "Bruno Bracegirdle",
    "Primrose Bracegirdle",
    "Brand",
    "Brandir",
    "Adaldrida (Bolger) Brandybuck",
    "Amaranth Brandybuck",
    "Borlach",
    "Esmeralda Brandybuck",
    "Estella (Bolger) Brandybuck",
    "Hilda Brandybuck",
    "Madoc Brandybuck",
    "Melilot Brandybuck",
    "Mentha Brandybuck",
    "Borin",
    "Mirabella (Took) Brandybuck",
    "Primula (Brandybuck) Baggins",
    "Seredic Brandybuck",
    "Brego",
    "Bregolas",
    "Bregor",
    "Sapphira (Brockhouse) Boffin",
    "Bucca of the Marish",
    "Asphodel (Brandybuck) Burrows",
    "Milo Burrows",
    "Celandine Brandybuck",
    "Bëor",
    "Bór",
    "Calimehtar",
    "Minto Burrows",
    "Boron",
    "Meriadoc Brandybuck",
    "Calmacil",
    "Celeborn",
    "Celebrimbor",
    "Celebrindor",
    "Celebrían",
    "Celegorm",
    "Celepharn",
    "Cemendur",
    "Cemendur (son of Axantur)",
    "Ceorl",
    "Caliondo",
    "Cirion",
    "Ciryandil",
    "Ciryatur",
    "Ciryon",
    "Bowman Cotton",
    "Lily Cotton",
    "Marigold (Gamgee) Cotton",
    "Rosie Cotton",
    "Tolman Cotton",
    "Castamir the Usurper",
    "Curufin",
    "Círdan",
    "Dairuin",
    "Damrod",
    "User:Deathshriek",
    "Denethor (First Age)",
    "Falco Chubb-Baggins",
    "Caranthir",
    "Denethor II",
    "Diamond Took",
    "Dinodas Brandybuck",
    "Dior (Steward)",
    "Dodinas Brandybuck",
    "Dori",
    "Dorlas",
    "Denethor I",
    "Duinhir",
    "Durin VII",
    "Dwalin",
    "Dáin I",
    "Dervorin",
    "Déagol",
    "Déor",
    "Derufin",
    "Duilin",
    "Dáin II Ironfoot",
    "Déorwine",
    "Dírhael",
    "Dírhavel",
    "Dís",
    "Dúnhere",
    "Ecthelion II",
    "Ecthelion I",
    "Edrahil",
    "Egalmoth",
    "Eglantine (Banks) Took",
    "Eilinel",
    "Elatan",
    "Eldacar (King of Arnor)",
    "Eldarion",
    "Eldacar (King of Gondor)",
    "Elemmírë (elf)",
    "Elendil",
    "Elendur",
    "Elendur of Arnor",
    "Elboron",
    "Eldalótë",
    "Elenwë",
    "Elfhelm",
    "Elfhild",
    "Elfwine",
    "Elladan and Elrohir",
    "Emeldir",
    "Elphir",
    "Elrond",
    "Enel",
    "Enelyë",
    "Enerdhil",
    "Erchirion",
    "Erellont",
    "Erendis",
    "Erestor",
    "Eorl the Young",
    "Erkenbrand",
    "Estelmo",
    "Eradan",
    "Eärendur of Númenor",
    "Eärnil I",
    "Eärnil II",
    "Eärnur",
    "Eärwen",
    "Eärendur (Lord of Andúnië)",
    "Eöl",
    "Eärendil of Gondor",
    "Eärendur of Arnor",
    "Faramir (son of Ondoher)",
    "Fastred",
    "Fastred (Pelennor Fields)",
    "Fengel",
    "Ferumbras Took II",
    "Finarfin",
    "Findegil",
    "Findis",
    "Finduilas",
    "Finduilas of Dol Amroth",
    "Fingolfin",
    "Farin",
    "Fingon",
    "Finrod",
    "Finwë",
    "Flói",
    "Faramir",
    "Folca",
    "Fastolph Bolger",
    "Folcred",
    "Forlong",
    "Folcwine",
    "Fortinbras Took I",
    "Forthwini",
    "Forweg",
    "Freca",
    "Fram",
    "Frerin",
    "Frumgar",
    "Fréawine",
    "Frór",
    "Frár",
    "Fundin",
    "Fréa",
    "Fréaláf Hildeson",
    "Fëanor",
    "Fíriel",
    "Fíli and Kíli",
    "Galar",
    "Galadriel",
    "Galdor",
    "Galion",
    "Daisy Gamgee I",
    "Frodo Gardner",
    "Hamson Gamgee",
    "May Gamgee",
    "Samwise Gamgee",
    "Gamling",
    "Elanor Gardner",
    "Gelmir",
    "Hamfast Gamgee",
    "Halfred Gamgee",
    "Galdor of the Havens",
    "Gil-galad",
    "Gildis",
    "Gildor (Edain)",
    "Gildor Inglorion",
    "Gilfanon",
    "Ghân-buri-Ghân",
    "Gethron",
    "Gilraen",
    "Gelmir (of Angrod's kin)",
    "Girion",
    "Gimilzagar",
    "Glorfindel",
    "Glirhuin",
    "Gléowine",
    "Gimilkhâd",
    "Gimli",
    "Golasgil",
    "Goldwine",
    "Hanna (Goldworthy) Brandybuck",
    "Gorbulas Brandybuck",
    "Gorhendad (Oldbuck) Brandybuck",
    "Gorlim",
    "Glóin (King of Durin's Folk)",
    "Glóin",
    "Glóredhel",
    "Gormadoc Deepdelver Brandybuck",
    "Gram",
    "Holman Greenhand",
    "Rose Greenhand",
    "Grimbeorn",
    "Grimbold",
    "Grithnir",
    "Gróin",
    "Halfred Greenhand",
    "Erling Greenhand",
    "Guilin",
    "Hending Greenhand",
    "Grór",
    "Gundor",
    "Guthláf",
    "Hador",
    "Hador (Steward)",
    "Halbarad",
    "Haldir (Haladin)",
    "Gálmód",
    "Gwindor",
    "Haldir (Lorien)",
    "Haleth",
    "Gárulf",
    "Haleth (Helm's son)",
    "Hallacar",
    "Hallas (Steward)",
    "Halmir",
    "Hallatan",
    "Hamfast of Gamwich",
    "Hareth",
    "Harding",
    "Hardang",
    "Hathaldir",
    "Hatholdir",
    "Helm Hammerhand",
    "Hathol",
    "Handir",
    "Henderch",
    "Herefara",
    "Hendor",
    "Herion",
    "Herubrand",
    "Herucalmo",
    "Hirgon",
    "Hirluin",
    "Hob Gammidge",
    "Hob Hayward",
    "Tobias Hornblower",
    "Holfast Gardner",
    "Horn",
    "Hundad",
    "Hundar",
    "Hunthor",
    "Huor",
    "Hyarmendacil I",
    "Hyarmendacil II",
    "Háma",
    "Húrin II",
    "Háma (Helm's son)",
    "Húrin of Emyn Arnen",
    "Húrin",
    "Imin",
    "Iminyë",
    "Imlach",
    "Imrahil",
    "Imrazôr",
    "Idril",
    "Ibûn",
    "Indis",
    "Húrin I",
    "Ingwë",
    "Inzilbêth",
    "Ioreth",
    "Iorlas",
    "Isembold Took",
    "Ingold",
    "Isengrim Took III",
    "Indor",
    "Ingwion",
    "Isilmo",
    "Ivriniel",
    "Lalaith",
    "Larnach",
    "Legolas",
    "Isildur",
    "Lindir",
    "Lindissë",
    "Isilmë",
    "Lindo",
    "Ivorwen",
    "Lindórië",
    "Lenwë",
    "Lorgan",
    "Lothíriel",
    "Léod",
    "Brytta Léofa",
    "Lóni",
    "Lúthien",
    "Farmer Maggot",
    "Mablung the Ranger",
    "Maglor",
    "Maedhros",
    "Mahtan",
    "Magor",
    "Mairen",
    "Malach",
    "Maeglin",
    "Malvegil",
    "Manthor",
    "Manwendil",
    "Malva Headstrong Brandybuck",
    "Mallor",
    "Marach",
    "Marcho",
    "Mardil Voronwë",
    "Malbeth the Seer",
    "Marhwini",
    "Marmadas Brandybuck",
    "Master of Laketown",
    "Meneldil",
    "Meleth",
    "Meril-i-Turinqi",
    "Merimas Brandybuck",
    "Minohtar",
    "Marroc Brandybuck",
    "Marhari",
    "Minardil",
    "Mithrellas",
    "Morwen",
    "Morwen (Gondor)",
    "Morwë",
    "Míriel",
    "Mîm",
    "Narmacil I",
    "Nessanië",
    "Nimrodel",
    "Nerdanel",
    "Naugladur",
    "Nina Lightfoot",
    "Nolondil",
    "Niënor",
    "Nob",
    "Narmacil II",
    "Náin I",
    "Náin II",
    "Náli",
    "Nár",
    "Númendil",
    "Núneth",
    "Nurwë",
    "Nori",
    "Náin (father of Dáin II Ironfoot)",
    "Old Noakes",
    "Olwë",
    "Orchaldor",
    "Ondoher",
    "Ori",
    "Orodreth",
    "Orodreth (Steward)",
    "Oromendil",
    "Ohtar",
    "Ostoher",
    "Orophin",
    "Pelendur",
    "Mrs. Proudfoot",
    "Pengolodh",
    "Otho Sackville-Baggins",
    "Odo Proudfoot",
    "Radhruin",
    "Oropher",
    "Ragnir",
    "Ragnor",
    "Rían",
    "Rían (Gondor)",
    "Rowan Greenhand",
    "Rudigar Bolger",
    "Rufus Burrows",
    "Rómendacil I",
    "Lobelia Sackville-Baggins",
    "Rúmil (Noldo)",
    "Lotho Sackville-Baggins",
    "Sadoc Brandybuck",
    "Sador",
    "Saelon",
    "Rúmil of Lórien",
    "Sagroth",
    "Rómendacil II",
    "Silmariën",
    "Sangahyando",
    "Siriondil",
    "Saradas Brandybuck",
    "Robin Smallburrow",
    "Soronto",
    "Morwen Steelsheen",
    "Tar-Alcarin",
    "Ted Sandyman",
    "Tar-Aldarion",
    "Tar-Amandil",
    "Tar-Ancalimon",
    "Tar-Anárion",
    "Tar-Ardamin",
    "Tar-Atanamir",
    "Tar-Calmacil",
    "Tar-Ciryatan",
    "Tar-Elendil",
    "Tar-Ancalimë",
    "Tar-Palantir",
    "Tar-Súrion",
    "Tar-Minastir",
    "Tar-Míriel",
    "Tar-Telperiën",
    "Tar-Vanimeldë",
    "Tarannon Falastur",
    "Tar-Telemmaitë",
    "Tarcil",
    "Tar-Meneldur",
    "Targon",
    "Tata",
    "Tatië",
    "Tarciryan",
    "Telchar",
    "Telemnar",
    "Telumehtar",
    "The King of the Dead",
    "Tarondor",
    "Tarondor of Arnor",
    "User:Technobliterator/Showcase",
    "Thengel",
    "Thorondir",
    "Thranduil",
    "Thráin I",
    "Thorin II Oakenshield",
    "Thráin II",
    "Thorin III Stonehelm",
    "Thrór",
    "Théoden",
    "Théodred",
    "Tindómiel",
    "Thorin I",
    "Faramir Took I",
    "Isumbras Took I",
    "Fortinbras Took II",
    "Isumbras Took III",
    "Adalgrim Took",
    "Adamanta (Chubb) Took",
    "Isengrim Took II",
    "Adelard Took",
    "Ferumbras III Took",
    "Bandobras Took",
    "Hildifons Took",
    "Isembard Took",
    "Hildigrim Took",
    "Gerontius Took",
    "Hildibrand Took",
    "Paladin Took II",
    "Pearl Took",
    "Peregrin Took",
    "Rosa (Baggins) Took",
    "Sigismond Took",
    "Turgon",
    "Turgon (Steward)",
    "Túrin",
    "Tulkastor",
    "Tuor",
    "Turambar",
    "Uldor",
    "Túrin II",
    "Ulfang",
    "Ulfast",
    "Ulbar",
    "Túrin I",
    "Urthel",
    "Ulwarth",
    "Vairë (Elf)",
    "Valacar",
    "Valandil",
    "Valandur",
    "Valandil of Andúnië",
    "Vidugavia",
    "Vardamir Nólimon",
    "Vardilmë",
    "Vidumavi",
    "Vorondil",
    "Voronwë",
    "Vëantur",
    "Walda",
    "Willie Banks",
    "Wiseman Gamwich",
    "Wulf I",
    "Wídfara",
    "Írimë",
    "Óin",
    "Yávien",
    "Dora Baggins",
    "Largo Baggins",
    "Mimosa (Bunce) Baggins",
    "Pansy Baggins",
    "Polo Baggins",
    "Ponto Baggins I",
    "Bingo Baggins",
    "Chica (Chubb) Baggins",
    "Óin (King of Durin's Folk)",
    "Prisca (Baggins) Bolger",
    "Rudibert Bolger",
    "Theobald Bolger",
    "Adalgar Bolger",
    "Ruby (Bolger) Baggins",
    "Wilimar Bolger",
    "Camellia (Sackville) Baggins",
    "Everard Took",
    "Gundahar Bolger",
    "Ferdinand Took",
    "Pervinca Took",
    "Pimpernel Took",
    "Ferdibrand Took",
    "Reginard Took",
    "Flambard Took",
    "Lalia (Clayhanger) Took",
    "Ruby Gamgee",
    "Rudolph Bolger",
    "Tanta (Hornblower) Baggins",
    "Inigo Baggins",
    "Tanta Hornblower",
    "Tobold Hornblower",
    "Lily (Baggins) Goodbody",
    "Togo Goodbody",
    "Goldberry",
    "Bell (Goodchild) Gamgee",
    "Goldilocks (Gardner) Took",
    "Merry Gamgee",
    "Bilbo Gamgee",
    "Halfast Gamgee",
    "Rose Gamgee",
    "Pippin Gamgee",
    "Durin",
    "Poppy (Chubb-Baggins) Bolger",
    "Robin Gardner",
    "Primrose Gardner",
    "Hamfast Gardner",
    "Tolman Cotton Jr.",
    "Carl Cotton",
    "Wilcome Cotton",
    "Doderic Brandybuck",
    "Daisy Gamgee",
    "Berilac Brandybuck",
    "Gorbadoc Brandybuck",
    "Marmadoc Brandybuck",
    "Ilberic Brandybuck",
    "Orgulas Brandybuck",
    "Rorimac Brandybuck",
    "Merimac Brandybuck",
    "Salvia (Brandybuck) Bolger",
    "Bilbo Gardner",
    "Briffo Boffin",
    "Gruffo Boffin",
    "Lavender (Grubb) Boffin",
    "Uffo Boffin",
    "Bodo Proudfoot",
    "Sancho Proudfoot",
    "Olo Proudfoot",
    "Saradoc Brandybuck",
    "Nimloth (elf)",
    "Linda (Baggins) Proudfoot",
    "Gríma Wormtongue",
    "Gollum",
    "Legolas (elf of Gondolin)",
    "Gandalf",
    "Radagast",
    "Tilion",
    "Elemmakil",
    "Saruman",
    "Sauron",
    "Eönwë",
    "Durin's Bane",
    "Alatar",
    "Arien",
    "Uinen",
    "Mosco Burrows",
    "Myrtle Burrows",
    "Pallando",
    "Moro Burrows",
    "Thingol",
    "Théodwyn",
    "Eärendil",
    "Harry Goatleaf",
    "Treebeard",
    "Witch-King of Angmar",
    "Mouth of Sauron",
    "Irolas",
    "Lagduf",
    "Fire-drake of Gondolin",
    "Angrim",
    "Angelimar",
    "Penlod",
    "Squint-eyed Southerner",
    "Fimbrethil",
    "Bill Ferny",
    "Fastred of Greenholm",
    "Falathar",
    "Elfstan Fairbairn",
    "Snaga (Two Towers orc)",
    "Snaga",
    "Smaug",
    "Seers",
    "Shelob",
    "Shagrat",
    "Scatha",
    "Salmar",
    "Sandyman",
    "Salgant",
    "Saeros",
    "Ruffian Leader",
    "Roäc",
    "Andwise Roper",
    "Rog",
    "River-woman",
    "Radbug",
    "Khîm",
    "Khamûl",
    "Irmo",
    "Eru Ilúvatar",
    "Ilmarë",
    "Hurin (Warden of the Keys)",
    "Huan",
    "Estë",
    "Éowyn",
    "Éomer",
    "Elwing",
    "Eluréd and Elurín",
    "Elros",
    "Elmo",
    "Egalmoth (elf)",
    "Ecthelion of the Fountain",
    "Ebor",
    "Ossë",
    "Oromë",
    "Orleg",
    "Orcobal",
    "Old Man Willow",
    "Hild",
    "Herumor (Fourth Age)",
    "Herumor",
    "Mat Heathertoes",
    "Haldar",
    "Haldad",
    "Draugluin",
    "Dior",
    "Dina Diggle",
    "Daeron",
    "Óin (King of Durin's Folk)",
    "Óin",
    "mar",
    "bal",
    "Írimë",
    "Írildë",
    "Éothain",
    "Éomund",
    "Éofor",
    "Zamîn",
    "Yavanna",
    "Tom Bombadil",
    "Bolg",
    "Boldog (Character)",
    "Bodruith",
    "Berúthiel",
    "Nienna",
    "Nielíqui",
    "Nessa",
    "Nellas",
    "Nauglath",
    "Narvi",
    "Nahar",
    "Mûmakil",
    "Muzgash",
    "The Moth",
    "Minastan",
    "Meneldor",
    "Men",
    "Melkor",
    "Melian",
    "Mauhúr",
    "Manwë",
    "Mandos",
    "Gwaihir",
    "Grishnákh",
    "Great Goblin",
    "Gothmog (Lieutenant of Morgul)",
    "Gothmog",
    "Gostir",
    'Gormadoc "Deepdelver" Brandybuck',
    "Gorgol",
    "Gorbag",
    "Golfimbul",
    "Glaurung",
    "Gimli (Elf)",
    "Gilmith",
    "Cottar",
    "Cora Goodbody",
    "Carcharoth",
    "Carc",
    "Calimmacil",
    "Barliman Butterbur",
    "Witch-king of Angmar",
    "Wife of Barach",
    "Widow Rumble",
    "Will Whitfoot",
    "Watcher in the Water",
    "Warg Matriarch",
    "Vëannë",
    "Varda",
    "Vairë",
    "Ungoliant",
    "Ulrad",
    "Ulmo",
    "Uglúk",
    "Ufthak",
    "Daddy Twofoot",
    "Tulkas",
    "Beleg",
    "Beechbone",
    "Barahir (Fourth Age)",
    "Baldor",
    "Balcmeg",
    "Man in the Moon",
    'Malva "Headstrong" Brandybuck',
    "Malantur",
    "Mallor (BOH)",
    "Mablung",
    "Lungorthin",
    "Lugdush",
    "Letter 211",
    "Landroval",
    "Gamil Zirak",
    "Galdor of the Tree",
    "Galathil",
    "Galador",
    "Fíriel Fairbairn",
    "Fuithluin",
    "Fuinur",
    "Fladrif",
    "Broncho Stonecrow",
    "Brodda",
    "Bregalad",
    "Tolman Gardner",
    "Tom, Bert, and William",
    "Tim",
    "Thuringwethil",
    "Thorondor",
    "Azog",
    "Aulë",
    "Asgon",
    "Artamir",
    "Ancalagon",
    "Andvír",
    "Amlach",
    "Aghan",
    "Agathor",
    "Aerandir",
    "Freda",
    "Sharku",
    "Madril",
    "Gothmog",
    "Morwen",
    "Figwit",
    "MINOR_CHARACTER",
    "MINOR_CHARACTER",
    "Éothain",
  ],
};
